<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















?>
<form method='get' action='<?php echo $url; ?>invoice.pag'><table><tr><td>Factuur Nummer:</td><td><input type='text' name='iid'></td><td><input type='submit' value='Vraag Op'></td></tr></table></form>
<?php
if ( isset ( $_GET['iid'] ) )
 {
  $id = $_GET['iid'];
  echo "<hr>";
  echo $id;

	#
	# V R A A G  V A N A F   I D   O P . . . . 
	#

		$INVOICE = array(); // Factuur In`t Engels
		
	#
	# T I J D E L I J K   U N I E K   I D   M E E G E V E N 
	#

  echo "<hr>".uniqueid();
 }
?>