<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















function _adminguestbook() {
 global $conf,$lang;
 $r = null;
	if ( isset ( $_GET['id'] ) )
	 {
	  $a = $conf['database']['db'] -> query("DELETE FROM `{$conf['database']['pref']}guestbook` WHERE `id`='{$_GET['id']}'");
	  if ( $a )
		$r .= sprintf($lang['guestbook']['deleted'] . "<br>", $_GET['id']);
	  else
	    $r .= sprintf($lang['guestbook']['notdeleted'] . "<br>", $_GET['id']);
	 }
	 
	if ( isset ( $_POST['mail'] ) )
	 {
		$conf['database']['db'] -> query("DELETE FROM `{$conf['database']['pref']}config` WHERE `config` LIKE '%guestbook:mail%'");
		$a = $conf['database']['db'] -> query("INSERT INTO `{$conf['database']['pref']}config` (`config`)\nVALUES ('guestbook:mail={$_POST['mail']}');");
	 }
	
  $a = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}config` WHERE `config` LIKE '%guestbook:mail%'");
  $a = $conf['database']['db'] -> fetch($a, 'array');
  preg_match_all("$(.*)=(.*)$", $a[0]['config'], $cnf);
  
  if ( $cnf[2][0] ) { $q = ' Selected'; $w = null; }
  else              { $q = null; $w = ' Selected'; }
  
  $r .= "<table>\n <tr>\n  <td>\n   {$lang['guestbook']['emailshow']}\n  </td>\n  <td>\n   <form method='post' action='admin.pag?act=modules&mod=guestbook'>\n    <select name='mail'>\n     <option value='0'{$w}>\n      {$lang['guestbook']['false']}\n     </option>\n     <option value='1'{$q}>\n      {$lang['guestbook']['true']}\n     </option>\n    </select>\n  </td>\n  <td>\n   <input type='submit' value='{$lang['guestbook']['save']}'>\n   </form>\n  </td>\n </tr>\n</table>\n<br><br>\n";

  $b = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}guestbook` ORDER BY `datetime` DESC");
  $b = $conf['database']['db'] -> fetch($b, 'array');
  
  $r .= "<table>";
  for ( $i=0; $i<sizeof($b); $i++ )
  {
	$b[$i]['datetime'] = nldate ( $b[$i]['datetime'] ) ;
	
		$b[$i]['text']     = preg_replace("#<(B|b)(r|R|r /|R /)>#",null,$b[$i]['text']);
	$b[$i]['text']     = preg_replace("@<P>&nbsp;</P>@",null,$b[$i]['text']);
	$b[$i]['text']     = preg_replace("@\\\'@","'",$b[$i]['text']);
  $b[$i]['text']     = preg_replace("@100%@","10%",$b[$i]['text']);
  $b[$i]['text']     = preg_replace("@top: (.*);@",null,$b[$i]['text']);
  $b[$i]['text']     = preg_replace("@left: (.*);@",null,$b[$i]['text']);
  $b[$i]['text']     = preg_replace("@position: (.*);@",null,$b[$i]['text']);
$ip=decodeip($b[$i]['ip']);

   $r .= "<tr>\n <td>\n  {$b[$i]['name']} @ $ip /DT: {$b[$i]['datetime']}\n </td>\n <td>\n  :\n </td>\n <td>\n  {$b[$i]['text']}\n </td>\n <td>\n  <form method='get' action='admin.pag'>\n   <input type='hidden' name='act' value='modules'>\n   <input type='hidden' name='mod' value='guestbook'>\n   <input type='hidden' name='id'  value='{$b[$i]['id']}'>\n   <input type='submit' value='{$lang['guestbook']['del']}' onclick=\"return confirm('" . sprintf($lang['guestbook']['dele'],$b[$i]['id']) . "');\">\n  </form>\n </td>\n</tr>";
  }
  $r .= "</table>";
  return $r;
}
?>