<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















 # {REP}
 
 ///Hier Komt Het IMPLENTATIE!
function last_guestbook ( $par = null )
{
  global $conf;
  $do = $conf['database']['db']->query("select * from `{$conf['database']['pref']}guestbook` ORDER BY `datetime` DESC limit 0,1;");
  $doe = $conf['database']['db']->fetch($do,'array');
    $text     = $doe[0]['text'];
	$text     = preg_replace("#<(B|b)(r|R|r /|R /)>#",null,$text);
	$text     = preg_replace("@<P>&nbsp;</P>@",null,$text);
	$text     = preg_replace("@\\\'@","'",$text);
  $text     = preg_replace("@100%@","10%",$text);
  $text     = preg_replace("@top: (.*);@",null,$text);
  $text     = preg_replace("@left: (.*);@",null,$text);
  $text     = preg_replace("@position: (.*);@",null,$text);
  return "(" . $doe[0]['name'] . ' @ ' . $doe[0]['datetime'] . ")&nbsp;" . $text; 
}

function get_guestbook ( $par = null ) 
 {
  global $conf;
  
  // $conf['database']['db'];
  $do = $conf['database']['db']->query("select * from `{$conf['database']['pref']}guestbook` ORDER BY `datetime` DESC;");
  $doe = $conf['database']['db']->fetch($do,'array');
echo "<div>";
  for ( $i=0; $i<sizeof($doe); $i++ )
  {
	$id       = $doe[$i]['id'];
	$name     = $doe[$i]['name'];
	$ip       = decodeip($doe[$i]['ip']);
	$email    = $doe[$i]['email'];
	$datetime = nldate($doe[$i]['datetime']);
	$text     = $doe[$i]['text'];
	$text     = preg_replace("#<(B|b)(r|R|r /|R /)>#",null,$text);
	$text     = preg_replace("@<P>&nbsp;</P>@",null,$text);
	$text     = preg_replace("@\\\'@","'",$text);
  $text     = preg_replace("@100%@","10%",$text);
  $text     = preg_replace("@top: (.*);@",null,$text);
  $text     = preg_replace("@left: (.*);@",null,$text);
  $text     = preg_replace("@position: (.*);@",null,$text);
  //top: 0; left: 0;
	if ( $conf['guestbook']['mail'] ) 
		{ 
			echo "
        <!-- Comment ID: {$id} -->\n
          <div class='Guestbook_value_M'>\n 
            <div class='Guestbook_title'>\n  
              <a href='mailto:{$email}'>Mail</a> <a href='{$conf['site']['url']}profile/{$name}'>{$name}</a> @ {$datetime}\n 
            </div>\n 
            <div class='Guestbook_message'>\n
              {$text}\n 
            </div>\n
          </div>
        <br>\n\n";
		}
    else
		{
			echo "<!-- Comment ID: {$id} -->\n
              <div class='Guestbook_value_U'>\n 
               <div class='Guestbook_title'>\n <a href='{$conf['site']['url']}/profile/{$name}'>{$name}</a> @ {$datetime}\n </div>\n 
               <div class='Guestbook_message'>\n  {$text}\n </div>\n
              </div>
            <br>\n\n";
		}
  }
  
 }
 
function post_guestbook ( $par = null ) 
 {
	  global $conf,$lang,$url;
	  $form=1;
	  if (
		   isset ( $_POST [ 'name' ] ) &&
		   isset ( $_POST [ 'email' ] ) &&
		   isset ( $_POST [ 'text' ] )
		 )
	  { 
	   if ( captcha ( ) Or defined("login") ) {
		if ( checkmail ( $_POST['email'] ) Or defined("login") )
		{
	  // $conf['database']['db'];
	  //$do = $conf['database']['db']->query("select * from `guestbook`;");

		$name     = $_POST['name'];
		$email    = $_POST['email'];
		$text     = nl2br($_POST['text']);
		$ip		  = encodeip(getip(true));
		$form     = 0;
		
		$p = $conf['database']['db']->query("INSERT INTO `{$conf['database']['pref']}guestbook` (`id` ,`name` ,`ip` ,`email` ,`datetime` ,`text`)\nVALUES (NULL , '{$name}', '{$ip}', '{$email}', NOW(), '{$text}');");
		
		if ( $p ) 
			{
				echo "<div class='info'>" . $lang['guestbook']['messagesend'] . '</div>';
			}
		else
			{
				echo "<div class='error'>" . $lang['guestbook']['messagenot'] . "</div>";
			}
		}
		else
		{
			echo "<div class='error'>" . $lang['guestbook']['fakeemail'] . "</div>";
		}
	 }
	 else
	 {
		echo "<div class='error'>" . $lang['guestbook']['wrongcaptcha'] . "{$_SESSION['captcha']}</div>";
	 }
 }
 if ($form)
 {
global $member;
?>
<div>
<form method="POST" action="<?php echo $url . $_GET['pag']; ?>.pag">
	<table>
	<?php 
	if(!defined("login")) 
		{
	?>
		<tr>
			<td>
				<?php echo $lang['guestbook']['name']; ?>:
			</td>
			<td>
				<input type="text" name="name"<?php if(isset($_POST['name'])) { echo ' value="' . $_POST['name'] . '"'; } ?>>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $lang['guestbook']['email']; ?>:
			</td>
			<td>
				<input type="text" name="email"<?php if(isset($_POST['email'])) { echo ' value="' . $_POST['email'] . '"'; } ?>>
			</td>
		</tr>
		<tr>
			<td>
				<img src="captcha.png"><br><small><?php echo $lang['guestbook']['captcha']; ?></small>
			</td>
			<td>
				<input type="text" name="captcha">
			</td>
		</tr>
	<?php
		}
		else
		{
	?>
		<input type="hidden" name="name" value="<?php echo $member['realname']; ?>">
		<input type="hidden" name="email" value="<?php echo $member['email']; ?>">
	<?php
		}
	?>
	</table>
				<?php echo wysiwyg("text"); ?>
				<?php echo $lang['guestbook']['text']; ?>
				<br>
				<textarea name="text" id="text" cols="45" rows="15"><?php if(isset($_POST['text'])) echo $_POST['text']; ?></textarea>
	<table>
		<tr>
			<td>
				<input type="reset" value="Reset">
			</td>
			<td>
				<input type="submit" value="Post">
			</td>
		</tr>
	</table>
</form>
</div>
<?php
 }
}

#load this function automatical
$wdgssautoload[] = array("lastgb",last_guestbook());
?>