<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















function _adminthemetester() 
{
 global $conf,$lang,$url;

				$themes = array();
				$o = opendir('template');
				while ( ( $f = readdir ( $o ) ) !== false ) 
				{
				 if ( $f != '.' && $f != '..' && is_dir("template/" . $f) && $f != 'admin' && $f != 'smilies' )
				  $themes[] = '<option name=\'' . $f .'\'' . (($conf['site']['theme']==$f)?' Selected':null) . '>' . $f . '</option>';
				}
				sort($themes);
				$themes = implode('',$themes);
        echo '<form method=\'get\' target=\'_blank\' action=\''.$url.'page/home\'><select name=\'theme\'>'.$themes.'</select><input type=\'submit\' value=\'test!\'>';
?>
<?php
}

?>