<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















function _admincaptcha() {
 global $conf,$lang;
  //return "Not Done Yet";
/*
captcha:length=5
captcha:height=30
captcha:square=1
captcha:chars=ABCDFGHJKLMNPQRSTUVWXY23456789
captcha:bgcolor=trans
captcha:lines=1
captcha:over=0
*/

 $a = $conf['database']['db'] -> query("SELECT `config` FROM `{$conf['database']['pref']}config` WHERE `config` like '%captcha%'");
 $a = $conf['database']['db'] -> fetch($a, 'array');
 
		$r = null;
		
		if ( isset ( $_POST['del'] ) )
			{
				$_POST['del'] = secure($_POST['del']);
				if ( $conf['database']['db'] -> query ($q = "DELETE FROM `{$conf['database']['pref']}config` WHERE `config` = '{$_POST['del']}' LIMIT 1") )
					{
						$r .= sprintf($lang['admin']['deleted'],$_POST['del']) . "<br>";
					}
				else
					{
						$r .= sprintf($lang['admin']['errdeleted'],$_POST['del']) . "<br>";
					}
			}
		
		if ( isset ( $_POST['make'] ) ) 
			{
				if ( is_array ( $_POST['make'] ) ) 
					{
						$conp = $_POST['make'][0];
						$_POST['make'] = secure($_POST['make'][0] . '=' . $_POST['make'][1]);
					}
				else
					{
						$_POST['make'] = secure($_POST['make']);
						$conp          = secure($_POST['make']);
					}
				
				if ( $conf['database']['db'] -> query ( $q = "INSERT INTO `{$conf['database']['pref']}config` ( `config` ) \n VALUES ( '{$_POST['make']}' );") )
					{
						$r .= sprintf($lang['admin']['updated'],$conp) . "<br>";
					}
				else
					{
						$r .= sprintf($lang['admin']['errupdated'],$conp) . "<br>";
					}
					$r .= renew(5,$conf['site']['url'] . "admin/module/captcha");
			}
			else
			{
				$r.= "<br><table>";
				
				for ( $i=0; $i<sizeof($a); $i++ )
				{
					preg_match_all("#(.*)\:(.*)=(.*)#",$a[$i]['config'],$out);
					$ex = explode("=",$a[$i]['config']);
					if ( !isset ( $ex[1] ) ) $ex[1]=null;
					$r .= "<tr><td>{$ex[0]}</td><td><form method='post' action='{$conf['site']['url']}admin/module/captcha'><input type='hidden' name='del' value='{$a[$i]['config']}'><input type='hidden' name='make[]' value='{$ex[0]}'><input type='text' name='make[]' value='{$ex[1]}'></td><td><input type='submit' value='{$lang['admin']['save']}'></form></td></tr>";
}
				$r .= "</table>";
		}
		return $r;
}
?>