<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















 define('in_wdgss',true);     # SET SECURITY
 include "include/core.php";  # LOAD ALL THINGS
 # EX: Modules; Configs; Anti-Hack Stuff; &more;

	if ( preg_match ( "/img\.php/", $_SERVER['REQUEST_URI'] ) )
	{
	 header("location: " . $conf['site']['url']);
	}
	
	$act = ( isset ( $_GET['act'] ) ? $_GET['act'] : null ) ;
	
	if ( $act == "captcha" )
		{
			draw_captcha ( $conf ) ;
		}
	elseif ( $act == "email" )
		{
			draw_email ( $conf ) ;
		}
	elseif ( $act == 'profile' )
		{
			if ( isset ( $_GET['f'] ) )
			 { $what = secure($_GET['f']); }
			else
			 { $what = (isset($_SESSION['avatar'])?$_SESSION['avatar']:null); }
			 
			user_avatar ( $conf, $what ) ;
		}
	elseif ( $act == 'egg' )
		{
			$_SESSION['email'] = 'You Found Me Again';
			draw_email ( $conf );
		}
	else
		{
			draw_email ( $conf, "Error!" );
		}
?>