<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################
















define('in_wdgss',true);
include "include/conf.php";

if (
	 isset ( $_GET['theme'] ) &&
     isset ( $_GET['file'] )
   )
	{
		$extensions = array (
			 "jpeg" => "image/jpeg",
			 "jpg"  => "image/jpeg",
			 "png"  => "image/png",
			 "gif"  => "image/gif",
			 "js"   => "application/x-javascript",
			 "css"  => "text/css",
			 "html" => "text/html"
		);

		if ( file_exists ( "template/" . $_GET['theme'] . "/" . $_GET['file'] ) )
			{
				$ext = explode(".",$_GET['file']);
				$ext = $ext[sizeof($ext)-1];
				if ( isset ( $extensions[$ext] ) )
					$e	=	$extensions[$ext];
				else
					$e	=	"application/octet-stream";

				header("content-type: $e");
				$f = file_get_contents("template/" . $_GET['theme'] . "/" . $_GET['file']);
				$f = preg_replace("#{wdg\:load}#",$conf['site']['url'] . "template/" . $_GET['theme'] . "/",$f);
				$f = preg_replace("#{wdg\:aload}#",$conf['site']['url'] . "template/admin/",$f);
					if ( $ext == 'js' Or $ext == 'css' Or $ext == 'html' )
						{
							ob_start();
								$f = eval("/*haystack*/ ?>" . $f . "<?php /*haystack*/");
								$f = ob_get_contents();
							ob_end_clean();
						}
				echo $f;
			}
		else
			{
				exit('404');
			}
	}
else
	{
		exit('NI'); #this error is never but, beter error, then white page
	}
?>