<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















# id, hideprofile(1/0) username realname hiderealname email hideemail password website birthday hidebirthday status text
#  1=yes 2=no ||| 1=allones 2=friensonly 3=never | adress | << | -------- | ifex  | y-m-d  | <<< | See Down | ^ TXT ^
#		status -1=banned, 0=activate, 1=user, 2=vip, 3=moderator, 4=admin, 5=root
// // print_r($_POST);
// // echo captcha() ? "CO" : "CF";
// [hideprofile] => 0 
// [username] => demo 
// [realname] => demo 
// [hiderealname] => 0 
// [email] => demo@wdgss.nl 
// [hideemail] => 0 
// [password] => demo 
// [confirm] => demo 
// [website] => www.wdgss.nl 
// [day] => 1 
// [month] => 1
// [year] => 2011 
// [hidebirthday] => 0 
// [captcha] => 4422k 
 if ( 
		isset ( $_POST['hideprofile'] ) &&
		isset ( $_POST['username'] ) &&
		isset ( $_POST['realname'] ) &&
		isset ( $_POST['hiderealname'] ) &&
		isset ( $_POST['email'] ) &&
		isset ( $_POST['hideemail'] ) &&
		isset ( $_POST['password'] ) &&
		isset ( $_POST['confirm'] ) &&
		isset ( $_POST['website'] ) &&
		isset ( $_POST['day'] ) &&
		isset ( $_POST['month'] ) &&
		isset ( $_POST['year'] ) &&
		isset ( $_POST['hidebirthday'] )
    )
 {
 if ( captcha ( ) ) {
	if ( $_POST['password'] == $_POST['confirm'] )
		{
			$mail = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}users` WHERE `email`='{$_POST['email']}'");
			$mail = $conf['database']['db'] -> num ( $mail, 'row' );
			$user = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}users` WHERE `username`='{$_POST['username']}'");
			$user = $conf['database']['db'] -> num ( $user, 'row' );
			if ( checkmail ( $_POST['email'] ) )
			{
			if ( $mail == 0 && $user == 0 )
				{
					$pass = md55($_POST['password']);
					$a = $conf['database']['db'] -> query($sql=" INSERT INTO `{$conf['database']['pref']}users` (`id` ,`hideprofile` ,`username` ,`realname` ,`hiderealname` ,`email` ,`hideemail` ,`password` ,`website` ,`birthday` ,`hidebirthday` ,`status` ,`text`)\nVALUES (NULL, '{$_POST['hideprofile']}', '{$_POST['username']}', '{$_POST['realname']}', '{$_POST['hiderealname']}', '{$_POST['email']}','{$_POST['hideemail']}', '{$pass}', '{$_POST['website']}', '{$_POST['year']}-{$_POST['month']}-{$_POST['day']}', '{$_POST['hidebirthday']}', '1', 'Hoi, Ik Ben Nieuw');");
//echo dump($conf['database']['db'] -> debug);
					if ( $a )
						{
							echo $lang['register']['maked'];
						}
					else
						{
							echo $lang['register']['error'];
						}
				}
			else
				{
					echo $lang['register']['errorusermail'];
				}
			}
			else
			{
				echo $lang['register']['erroruserfakemail'];
			}
			
		}
	else
		{
			echo $lang['register']['passnotmatch'];
		}
 }
 else
 {
 echo "Wrong Captcha!";
 }
 }
?>
<form method='post' action='<?php echo $conf['site']['url']; ?>page/register'>
	<table>
		<tr>
			<td>
				<?php echo $lang['register']['hideprofile']; ?>
			</td>
			<td>
				<select name='hideprofile'>
					<option value='0'>
						<?php echo $lang['register']['no']; ?>
					</option>
					<option value='1'>
						<?php echo $lang['register']['yes']; ?>
					</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $lang['register']['username']; ?>
			</td>
			<td>
				<input type='text' name='username'>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $lang['register']['realname']; ?>
			</td>
			<td>
				<input type='text' name='realname'>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $lang['register']['hiderealname']; ?>
			</td>
			<td>
				<select name='hiderealname'>
					<option value='0'>
						<?php echo $lang['register']['no']; ?>
					</option>
					<option value='1'>
						<?php echo $lang['register']['yes']; ?>
					</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $lang['register']['email']; ?>
			</td>
			<td>
				<input type='text' name='email'>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $lang['register']['hideemail']; ?>
			</td>
			<td>
				<select name='hideemail'>
					<option value='0'>
						<?php echo $lang['register']['no']; ?>
					</option>
					<option value='1'>
						<?php echo $lang['register']['yes']; ?>
					</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $lang['register']['password']; ?><br>
				<?php echo $lang['register']['confirm']; ?>
			</td>
			<td>
				<input type='password' name='password'><br>
				<input type='password' name='confirm'>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $lang['register']['website']; ?>
			</td>
			<td>
				http://<input type='text' name='website'>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $lang['register']['birthday']; ?>
			</td>
			<td>
				<?php
				 $aname = array ( 
									"day", 
									"month", 
									"year" 
								);
								
				 $array = array ( 
								 array ( 
									1,
									31
								 ),
								 array (
									1,
									12
								 ),
								 array ( 
									(date("Y") - 120),
									(date("Y") + 120)
								 )
							    );
							  
				for ( $w=0; $w<sizeof($array); $w++ )
				{
				 echo "<select name='{$aname[$w]}'>";
				 for ( $i=$array[$w][0]; $i<$array[$w][1]+1; $i++ ) 
				 {
				  $a = ($i==date("Y"))?' Selected':null;
				  echo "<option value='{$i}'{$a}>{$i}</option>";
				 }
				 echo "</select>";
				}
				?>
			</td>
		</tr>
		<tr>
			<td>
				<?php echo $lang['register']['hidebirthday']; ?>
			</td>
			<td>
				<select name='hidebirthday'>
					<option value='0'>
						<?php echo $lang['register']['no']; ?>
					</option>
					<option value='1'>
						<?php echo $lang['register']['yes']; ?>
					</option>
				</select>
			</td>
		</tr>
		<tr>
			<td>
				<img id='ca' name='ca' class='ca' src='<?php echo $conf['site']['url']; ?>captcha.png'><br>
				<a href='/page/register' onclick="javascript:document.getElementById('ca').src='<?php echo $conf['site']['url']; ?>captcha.png';return false;">Refresh Captcha!</a>
			</td>
			<td>
				<input type='text' name='captcha'>
			</td>
		</tr>
		<tr>
			<td>
				<input type='reset' value='<?php echo $lang['register']['reset']; ?>'>
			</td>
			<td>
				<input type='submit' value='<?php echo $lang['register']['submit']; ?>'>
			</td>
		</tr>
	</table>
</form>