<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################
















if ( isset ( $_GET['thisistotrickyou'] ) )
 exit("var disabled = true;");
 
$add = "<script type=\"text/javascript\" language=\"javascript\">var disabled = false;</script>\r\n" .
"<script type=\"text/javascript\" src=\"{$conf['site']['url']}?thisistotrickyou=banner/popup.js/Or/advertisement.js\"></script>\r\n".
"<script type=\"text/javascript\" language=\"javascript\">
if(!disabled) {
 //alert(\"Please DISABLE your Adblocking Software\"); 
 overlay('<div style=\"margin:-10px 10px 10px 10px;\"><h3>&nbsp;&nbsp;&nbsp;{$conf['site']['name']}:</h3></div><br/><div style=\"min-height:115px;margin:0px 10px 0px 10px;\"><center>Please DISABLE your Adblocking Software</center></div>',true);
}
</script>";

//$wdgssautoload[] = array("adblock",$add);
$wdgssautoload[] = array("adblock",null);

?>