<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-4  v                   ###
	  ### REWRITTEN BY: ^ ^ ^ / FILEVER: 5             ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################

	function fix_get_id ( $w ) 
	{
	 	  preg_match("#(.*)(-|/)(.*)(-|/)(.*)#", $w, $match);
		  return array($match[3],$match[1] . '-' . $match[3] . '-' . $match[5]);
	}
	
	function get_times ( )
	{
	 $a = array();
	 for ( $i=0; $i<24; $i++ )
	 {
	  $r = ( ( $i ) < 10 ) ? '0' . ($i) : ($i) ;
	  for ( $z=0; $z<(60/5); $z++ )
	  { 
	   $e = ( ( $z * 5 ) < 10 ) ? '0'.($z*5) : ($z*5) ;
	   $X = $r . ':' . $e;
	   $a[] = "<option value='{$X}' name='{$X}'" . ( ( ( $X == '12:00' ) ? ' selected=\'true\'' : null ) ) . ">{$X}</option>\r\n"; 
	  } 
	 }
	 return implode(null,$a);
	}
		
	if ( isset ( $_GET['id'] ) )
	{
		  $match 		 = fix_get_id($_GET['id']);
		  $_GET['month'] = $match[0];
		  $_GET['id']    = $match[1];
	}

echo "<table><tr><td>";
$c = $conf['database']['db'];

	if ( isset ( $_SESSION['login'] ) && isset ( $_SESSION['status'] ) && @$_SESSION['status'] >= 3 )
	 $EX = '';
	else
	 $EX = ' WHERE `hidebirthday`=\'0\'';
 
$d = $c -> query ( "SELECT `username`,`birthday` FROM `{$conf['database']['pref']}users`{$EX};" ) ;
$n = $c -> num ( $d, 'row' ) ;
$d = $c -> fetch ( $d, 'array' ) ;
$agenda = array ( ) ;
$ag     = array ( ) ;
# id 	omschrijving 	door 	datum 	tijd1 	tijd2
for ( $i=0; $i<sizeof($d); $i++ )
 {
  preg_match("#(.*)-(.*)-(.*)#", $d[$i]['birthday'], $match);
  $x = array (
						'Verjaardag Van: ' . $d[$i]['username'],
						"{$d[$i]['username']} Woord " . age($d[$i]['birthday']) . ".<br>Nog Vele Jaren <br>Met Vriendelijk Groeten,<br>Team {$conf['site']['name']}",
						( $match [ 3 ] = ( ( ( $match [ 3 ] < 10 ) && ( strlen ( $match [ 3 ] ) == 1 ) ) ? '0' . $match [ 3 ] : $match [ 3 ] ) ),
						( $match [ 2 ] = ( ( ( $match [ 2 ] < 10 ) && ( strlen ( $match [ 2 ] ) == 1 ) ) ? '0' . $match [ 2 ] : $match [ 2 ] ) ),
						date("Y"),
						'Team ' . $conf['site']['name'],
						'00:00',
						'00:00'
					);
	$ag[$match[3] . '-' . $match[2] . '-' . date('Y')] = array($x[0], $x); #FIX: $match[1]=date(y);
 }
$d = $c -> query ( "SELECT * FROM `{$conf['database']['pref']}agenda`;" ) ;
$n = $c -> num ( $d, 'row' ) ;
$d = $c -> fetch ( $d, 'array' ) ;
# id 	omschrijving 	door 	datum 	tijd1 	tijd2
for ( $i=0; $i<sizeof($d); $i++ )
 {
		$oms = preg_replace("#<(b|B)(r|R|r /|R /)>#",null,$d[$i]['omschrijving']);
		preg_match("#(.*)-(.*)-(.*)#", $d[$i]['datum'], $match);
		$x = array(
			inkorten($oms, 32),
			$d[$i]['omschrijving'],
			( $match [ 1 ] = ( ( ( $match [ 1 ] < 10) && ( strlen ( $match [ 1 ] ) == 1 ) ) ? '0' . $match [ 1 ] : $match [ 1 ] ) ),
			( $match [ 2 ] = ( ( ( $match [ 2 ] < 10) && ( strlen ( $match [ 2 ] ) == 1 ) ) ? '0' . $match [ 2 ] : $match [ 2 ] ) ),
			( $match [ 3 ] = ( ( ( $match [ 3 ] < 10) && ( strlen ( $match [ 3 ] ) == 1 ) ) ? '0' . $match [ 3 ] : $match [ 3 ] ) ),
			$d[$i]['door'],
			$d[$i]['tijd1'],
			$d[$i]['tijd2']
		);
	$ag[$match[1] . '-' . $match[2] . '-' . $match[3]] = array(inkorten($oms, 32), $x);
 }

$cfg 		  	= array();
$cfg['datum'] 	= date("d/m/Y"); 
$cfg['day'] 	= date("d"); # Day (1-31)
	if ( !isset ( $_GET['month'] ) ) 
		    $cfg['month'] 	= date("m"); # Month (1-12)
	else
		{
			$cfg['month'] 	= ( ( ( $_GET['month'] < 10 ) &&  ( strlen ( $_GET['month'] ) == 1 ) ) ? '0' . $_GET['month'] : $_GET['month'] ) ;	
		}

	if ( !isset ( $_GET['year'] ) ) 
		    $cfg['year'] 	= date("Y"); # Month (1-12)
	else
		{
			$cfg['year'] 	= $_GET['year'] ;	
		}

//$cfg['year'] 	= date("Y"); # The Year

$cfg['week'] 	= date("W"); # Week Number
$cfg['doy']     = date("z"); # Day Of Year
$cfg['dim']     = @cal_days_in_month(CAL_GREGORIAN,$cfg['month'],$cfg['year']) + 1; #Days In Month

echo "<a href='{$conf['site']['url']}agenda/" . date('d/m/Y') . "'>{$lang['agenda']['gotoday']}</a>";
echo "<table>";
echo sprintf("<tr>"	  . # SprintF
	 "<td>%s</td>"	  . # Week
	 "<td>%s</td>" 	  . # Monday
	 "<td>%s</td>" 	  . # Tuesday
	 "<td>%s</td>"    . # Wednesday
	 "<td>%s</td>" 	  . # Thursday
	 "<td>%s</td>"	  . # Friday
	 "<td>%s</td>"	  . # Saturday
	 "<td>%s</td>" 	  . # Sunday
	 "</tr>"	 	  , # </tr>!
$lang['agenda']['WK'] , # Week
$lang['agenda']['MO'] , # Monday
$lang['agenda']['TU'] , # Tuesday
$lang['agenda']['WE'] , # Wednesday
$lang['agenda']['TH'] , # Thursday
$lang['agenda']['FR'] , # Friday
$lang['agenda']['SA'] , # Saturday
$lang['agenda']['SU'] # # Sunday
) ;      # T R A N S L A T I O N
echo "<tr>";

$Z				= date("N", @mktime (1, 0, 0, $cfg['month'], 1, date('Y') ) ) - 1;

echo "<td>" . date("W",@mktime (1, 0, 0, $cfg['month'], 1, date('Y'))) . "</td>";
for ( $i=0; $i<$Z; $i++) 
	{ 
		echo "<td>&nbsp;</td>"; 
	}
	
$_W				=	$Z;
$cfg['Z']		= 	$Z;

###################################################################################################################################
/*DEBUG*/ #echo dump ( array ( $cfg, $ag ) ) ; ####################################################################################
###################################################################################################################################

for ( $i=01; $i<$cfg['dim']; $i++ )
	{
		$i = ( ( ( $i < 10 ) && ( sizeof ( $i ) == 1 ) ) ? '0' . $i : $i ) ;
		
		if ( $_W >= 7 )
			{
				echo "</tr><tr><td>" . date("W", mktime (1, 1, 1, $cfg['month'], $i, date('Y') ) ) . "</td>";
				$_W = 0;
			}
			
		$_W++;
		
		if ( isset ( $ag[$i . '-' . $cfg['month'] . '-' . $cfg['year']] ) )
			{
				if ( $i == $cfg['day'] && $cfg['month'] == date("m") )
				{
					echo "<td style=\"border: 2px; border-color: green; border-style: double;\"><a href='{$conf['site']['url']}agenda/" . $i . '/' . $cfg['month'] . '/' . $cfg['year'] . "' title='" . $ag[$i . '-' . $cfg['month'] . '-' . $cfg['year']][0] . "'><font color='red'><b><u>{$i}</u></b></font></a></td>";
				}
				else
				{
					echo "<td style=\"border: 1px; border-color: red; border-style: dotted;\"><a href='{$conf['site']['url']}agenda/" . $i . '/' . $cfg['month'] . '/' . $cfg['year'] . "' title='" . $ag[$i . '-' . $cfg['month'] . '-' . $cfg['year']][0] . "'><font color='red'><b><u>{$i}</u></b></font></a></td>";
				}
			}
		elseif ( $i == $cfg['day'] && $cfg['month'] == date("m") )
			{
				echo "<td style=\"border: 1px; border-color: green; border-style: dotted;\"><a href='{$conf['site']['url']}agenda/" . $i . '/' . $cfg['month'] . '/' . $cfg['year'] . "'><font color='green'><u><b>{$i}</b></u></font></a></td>";
			}
		else
			{
				echo "<td><a href='{$conf['site']['url']}agenda/" . $i . '/' . $cfg['month'] . '/' . $cfg['year'] . "' title='EMPTY'>{$i}</a></td>";
			}
	}

echo "</tr>";
$x1 = ($cfg['month']-1);
$x2 = ($cfg['month']+1);
echo 	"</table>" .
		"<br>";
/* back fix */
	if ( $x1 >= 1 ) 
		{
			echo "<a href='{$conf['site']['url']}agenda/month/" . ($x1) . "'>&lt;--({$x1})</a>";
		}
	else
		{
			echo "<a href='{$conf['site']['url']}agenda/month/" . ($x1+12) . "/" . ($cfg['year'] - 1) . "'>&lt;--(" . ($x1+12) . " `" . substr(($cfg['year'] - 1),2,4) . ")</a>";
		}
	
echo	"&nbsp;&nbsp;&nbsp;&nbsp;{$cfg['month']}&nbsp;&nbsp;&nbsp;&nbsp;";
/* next fix */
	if ($x2 <= 12) 
		{ 
			echo "<a href='{$conf['site']['url']}agenda/month/" . ($x2) . "'>({$x2})--&gt;</a>";
		}
	else
		{
			echo "<a href='{$conf['site']['url']}agenda/month/" . ($x2-12) . "/" . ($cfg['year'] + 1) . "'>(" . ($x2-12) . " `" . substr(($cfg['year'] + 1),2,4) . ")--&gt;</a>";
		}
	
echo "</td><td>";

	#CAT Selected? 
	if ( isset ( $_GET['id'] ) )
	{
	 if ( isset ( $ag[$_GET['id']][1] ) )
	  {
		if ( $ag[$_GET['id']][1][6] == $ag[$_GET['id']][1][7] )
			{
				$tijd = $lang['agenda']['wholeday'];
			}
		else
			{
				$tijd = $ag[$_GET['id']][1][6] . " {$lang['agenda']['tot']} " . $ag[$_GET['id']][1][7];
			}

	   echo "\r\n" .
			"<table>\r\n" .
			"<tr><td>{$lang['agenda']['title']}</td>	 <td>:</td><td>{$ag[$_GET['id']][1][0]}</td></tr>\r\n" .
			"<tr><td>&nbsp;</td> <td>&nbsp;</td> <td>&nbsp;</td> </tr>			 \r\n" .
			"<tr><td>{$lang['agenda']['by']}</td>	 <td>:</td><td><a href='{$conf['site']['url']}profile" .
			"/{$ag[$_GET['id']][1][5]}'>{$ag[$_GET['id']][1][5]}</a></td></tr>   \r\n" . 
			"<tr><td>&nbsp;</td> <td>&nbsp;</td> <td>&nbsp;</td> </tr>			 \r\n" .
			"<tr><td>{$lang['agenda']['message']}</td><td>:</td><td>{$ag[$_GET['id']][1][1]}</td></tr>\r\n" . 
			"<tr><td>&nbsp;</td> <td>&nbsp;</td> <td>&nbsp;</td> </tr>			 \r\n" .
			"<tr><td>{$lang['agenda']['time']}</td>   <td>:</td><td>{$tijd}</td></tr>				 \r\n" . 
			'<tr><td>' 																   .
#EDIT			( ( isset ( $_SESSION['login'] ) && (@$_SESSION['status'] >= 3) && ($ag[$_GET['id']][1][5] != 'Team ' . $conf['site']['name'])) ? '<a href=\'' . $conf['site']['url'] . 'agenda/edit/' . $_GET['id'] . '\'>Bewerk Item</a>' : null ) .
			'</td><td></td><td>' 															   .
			( ( isset ( $_SESSION['login'] ) && (@$_SESSION['status'] >= 3) && ($ag[$_GET['id']][1][5] != 'Team ' . $conf['site']['name'])) ? '<a href=\'' . $conf['site']['url'] . 'agenda/del/' . $_GET['id'] . '\' onclick="return confirm(\'' . $lang['agenda']['sure'] . '\');">' . $lang['agenda']['delitem'] . '</a>' : null ) .
			'</td></tr>'															   .
			'</table>'																   ;
	  }
	 else
	  {
	   echo "{$lang['agenda']['notexists']}<br>" .
	   ( ( isset ( $_SESSION['login'] ) && @$_SESSION['status'] >= 3) ? '<a href=\'' . $conf['site']['url'] . 'agenda/add/' . $_GET['id'] . '\'>' . $lang['agenda']['add'] . '</a>' : null );
	  }
	}
	
	elseif ( isset ( $_GET['add'] ) && isset ( $_SESSION['login'] ) ) 
	{
	 if (
		  isset ( $_POST [ 'text' ]  ) &&
		  isset ( $_POST [ 'date' ]  ) && 
		  isset ( $_POST [ 'time1' ] ) &&
		  isset ( $_POST [ 'time2' ] )
		)
	 {
	  $_POST['text'] = preg_replace("#\n#",null,$_POST['text']);
	  $sql = "
	  INSERT INTO `{$conf['database']['pref']}agenda` ( 
		`id` ,
		`omschrijving` ,
		`door` ,
		`datum` ,
		`tijd1` ,
		`tijd2` 
	  )
	  VALUES ( 
		NULL , 
		'{$_POST['text']}', 
		'{$_SESSION['login']}', 
		'{$_POST['date']}', 
		'{$_POST['time1']}', 
		'{$_POST['time2']}'
	  );";
	  $conf['database']['db']->query($sql);
	  #echo "Gemaakt! { $sql }" . mysql_error();
	  ga($conf['site']['url'] . 'agenda/' . $_POST['date']);
	 }
	 
	 $match = fix_get_id($_GET['add']);
	 preg_match("#(.*)-(.*)-(.*)#", $match[1], $eatch);
	 $what = $eatch[3] . '-' . $eatch[2] . '-' . $eatch[1];
	 
	 //echo 'maken';
	 echo "<form method='post' action='{$_SERVER['REQUEST_URI']}'>
	 <table>
	 <tr><td> {$lang['agenda']['message']} </td><td> <textarea name='text' id='text' rows='15' cols='50'> </textarea>" . wysiwyg('text') . "</td></tr>
	 <tr><td> {$lang['agenda']['time']}1 </td><td> <select name='time1'> " . get_times ( ) . " </select> </td></tr>
	 <tr><td> {$lang['agenda']['time']}2 </td><td> <select name='time2'> " . get_times ( ) . " </select> </td></tr>
	 <input type='hidden' name='date' value='{$_GET['add']}'>
	 </table><input type='submit'>
	 </form>";
	}
	
/*
	elseif ( isset ( $_GET['edit'] ) ) 
	{
	 $match = fix_get_id($_GET['edit']);
	 preg_match("#(.*)-(.*)-(.*)#", $match[1], $eatch);
	 $what = $eatch[3] . '-' . $eatch[2] . '-' . $eatch[1];

	 echo 'bewerken: ' . $what;
	} 
#*/

	elseif ( isset ( $_GET['del'] ) ) 
	{
	 $match = fix_get_id($_GET['del']);
	 preg_match("#(.*)-(.*)-(.*)#", $_GET['del'], $eatch);
	 $what = $_GET['del']; #;//JVN:7-8-2010
	 $d1   = ( ( substr ( $eatch[1], 0, 1) == 0) ? substr($eatch[1], 1, 2) : $eatch[1] ) . '-' . $eatch[2] . '-' . $eatch[3];
	 $d2   = $eatch[1] . '-' . ( ( substr ( $eatch[2], 0, 1) == 0) ? substr($eatch[2],1,2) : $eatch[2] ) . '-' . $eatch[3];
	 $d3   = ( ( substr ( $eatch[1], 0, 1) == 0) ? substr($eatch[1], 1, 2) : $eatch[1] ) . '-' . ( ( substr ( $eatch[2], 0, 1) == 0) ? substr($eatch[2], 1, 2) : $eatch[2] ) . '-' . $eatch[3];
	 $c -> query("DELETE FROM `{$conf['database']['pref']}agenda` WHERE `datum`='{$what}' Or `datum`='{$d1}' Or `datum`='{$d2}' Or `datum`='{$d3}';");
	 
#	 echo 'verwijderd: ' . $what . '<br>';
	 echo mysql_error ( ) . $c -> mmysql_error ( ) ; //ERROR?
	 renew(1,$conf['site']['url'] . 'agenda/' . $_GET['del']);
	}

	else
	{
	 echo "{$lang['agenda']['select']}";
	}
echo "</td></tr></table>";
?>