<table><tr><td>
<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















define('nlb',"<br />\r\n");

$pref=$conf['database']['pref'];

function printtijd()
{
$a=null;
for($i=0; $i<24; $i++)
{
if($i<10)
 $i = '0' . $i;
$a .= '<optgroup label="' . $i . '"><option name="' . $i . ':00" value="' . $i . ':00">' . $i . ':00</option><option name="' . $i . ':15" value="' . $i . ':15">' . $i . ':15</option><option name="' . $i . ':30" value="' . $i . ':30">' . $i . ':30</option><option name="' . $i . ':45" value="' . $i . ':45">' . $i . ':45</option></optgroup>';
}
$a .= '<optgroup label="24"><option name="24:00" value="24:00">24:00</option></optgroup>';
echo $a;
}

/* agenda stuk */
//Allereerst gaan we alle maanden defineren
$maanden     = array(
  1 => 'Januari',
  2 => 'Februari',
  3 => 'Maart',
  4 => 'April',
  5 => 'Mei',
  6 => 'Juni',
  7 => 'Juli',
  8 => 'Augustus',
  9 => 'September',
  10 => 'Oktober',
  11 => 'November',
  12 => 'December'
);

//De dagen in een week
$weekdagen    = array(
  'maandag',
  'dinsdag',
  'woensdag',
  'donderdag',
  'vrijdag',
  'zaterdag',
  'zondag'
);

//En de jaren die we willen toestaan, in dit geval van 2006 tot 2010.
$begin = 1300;
$max   = 10;

$jaren         = range($begin, date('Y')+$max); 


//Wat als er een maand in de url staat?
if(isset($_GET['maand']))
{
    //Eerst kijken we of die maand wel bestaat
    if(array_key_exists($_GET['maand'], $maanden)) 
    {
        $maand = $_GET['maand'];
    }else{
        $maand = date('n');
    }    
}else{
    $maand = date('n');
}

//Wat als er een jaar in de url staat?
if(isset($_GET['jaar']))
{
    //Eerst kijken we of we dat jaar wel goedkeuren
    if(in_array($_GET['jaar'],$jaren))
    {
        $jaar = htmlentities($_GET['jaar']);
    }else{
        $jaar = date('Y');
    }    
}else{
    $jaar = date('Y');
}

//Omdat we nu het jaar en de maand weten kunnen we vaststellen welke dagen zijn toegestaan
$dagen = range(1,date('t', mktime(0,0,0,$maand,1,$jaar)));

//Wat als er een dag in de url staat?
if(isset($_GET['dag']))
{
    //Bestaat deze dag wel? 
    if(in_array($_GET['dag'], $dagen)) 
    {
        $dag = htmlentities($_GET['dag']);
    }else{
        $dag = 1;
    }    
}else{
    //Wat als er geen dag is geselecteerd? Dan kijken we of het vandaag dezelfde maand is als wat er is opgevraagd en selecteren we vandaag!
    if($maand == date('n'))
    {
        $dag = date('j');
    }else{
        $dag = 1;
    }
}

//Tijd voor een formuliertje! 
echo '<form action="" method="GET">';

//We maken een selectbox met daarin een foreach met alle maanden
echo '<select name="maand" onchange="this.form.submit()">';
foreach($maanden as $maandnummer => $maandnaam)
{
    if($maandnummer == $maand)
    {
        echo '<option selected value="'.$maandnummer.'">'.$maandnaam.'</option>';
    }else{
        echo '<option value="'.$maandnummer.'">'.$maandnaam.'</option>';
    }
}
echo '</select> ';

//Vervolgens maken we een selectbox voor alle jaren
echo '<select name="jaar" onchange="this.form.submit()">';
foreach($jaren as $jaarnummer)
{
    if($jaarnummer == $jaar)
    {
        echo '<option selected value="'.$jaarnummer.'">'.$jaarnummer.'</option>';
    }else{
        echo '<option value="'.$jaarnummer.'">'.$jaarnummer.'</option>';
    }
}
echo '</select></form><hr>';
$wesweek=date('W');
//Nu word het tijd om een mooi tabelletje te maken
echo "Weeknummer: " . date('W') . nlb;

echo "Datum Vandaag: " . date("d-m-Y",strtotime('+0 day')) . nlb;
echo 'Geselecteerd ' . $maand. ' / ' . $jaar . '<table>';

//We echoén alvast de bovenste rij
echo '<tr><th>wk</th><th>M</th><th>D</th><th>W</th><th>D</th><th>V</th><th>Z</th><th>Z</th></tr><tr>';

//Wat is de eerste dag van de maand?
$eerstedag = date('w', mktime(0,0,0,$maand,1,$jaar));
$weekjezzz = date('W', mktime(0,0,0,$maand,1,$jaar)); 
    if($weekjezzz==$wesweek)
    {
     $weekjezzz='<font color=\'red\'>' . $wesweek . '</font>';
    }
echo '<td>'.$weekjezzz.'</td>';
//Deze hebben we nodig om wat lege ruimte te vullen als de week niet begint op maandag.
for($nummer = 1; $nummer <= 6; $nummer += 1)
{
    if($nummer != $eerstedag)
    {
        echo '<td></td>';
    }else{
        $nummer = 7;
    }
}
    
//Voor iedere dag in de week gaan we nu een loopje beginnen!
foreach($dagen as $dag2)
{
    //Welke weegdag is het?
    $dagindeweek = date('w', mktime(0,0,0,$maand,$dag2,$jaar));
    $weekjenumme = date('W', mktime(0,0,0,$maand,$dag2,$jaar));
    if($weekjenumme==$wesweek)
    {
     $weekjenumme='<font color=\'red\'>' . $wesweek . '</font>';
    }
    //Als het 1 is (maandag) begint er een nieuwe rij!
    if($dagindeweek == 1)
    {
        echo '<tr><td>'.$weekjenumme.'</td>';
    } 
    
    //Stel dat het toevallig dezelfde datum als vandaag is? Dan willen we een rood randje!
    if(($dag2 == date('j')) && ($maand == date('n')) && ($jaar == date('Y'))/* && $dag2 != $dag*/)
    {
        echo '<td style="border: 1px solid red;" align="center">'; 
    }
//    elseif($dag2 == $dag){
//        echo '<td style="border: 1px solid blue;" align="center">';     
//    }
    else{
        echo '<td>'; 
    }    

    //Stel dat het toevallig dezelfde dag is als de dag die we geselecteerd hebbeb? Dan willen we bold!
    if($dag2 == $dag)
    {
        echo '<a href="?dag='.$dag2.'&amp;maand='.$maand.'&amp;jaar='.$jaar.'"><b><font color=\'green\'>'.$dag2.'</font></b></a></td>';
    }else{
        echo '<a href="?dag='.$dag2.'&amp;maand='.$maand.'&amp;jaar='.$jaar.'">'.$dag2.'</a></td>';
    }
    
    //Als het dag 0 is (zondag) willen we de rij eindigen!
    if($dagindeweek == 0)
    {
        echo '</tr>';
    }    
}

//Sluiten die handel! Huppakee!
echo '</table>';

//Uiteraard willen we een vorige maand...
if($maand == 1)
{
    echo '<br><a href="?maand=12&amp;jaar='.($jaar-1).'"><< Vorige</a>';
}else{
    echo '<br><a href="?maand='.($maand-1).'&amp;jaar='.$jaar.'"><< Vorige</a>';
}

//... en volgende maand knopje! Als het Januari of December is doen er uiteraard 1 jaar eraf of erbij.
if($maand == 12)
{
    echo ' | <a href="?maand=1&amp;jaar='.($jaar+1).'">Volgende >></a>';
}else{
    echo ' | <a href="?maand='.($maand+1).'&amp;jaar='.$jaar.'">Volgende >></a>';
}


if(isset($_GET['verwijder']))
{
/*
                <form method='get'><input type='hidden' name='verwijder' value='xdel'><input type='hidden' name='tijd1' value='<?php echo $data['tijd1']; ?>'><input type='hidden' name='datum' value='<?php echo $datum; ?>'><input type='submit' value='verwijder afspraak'></form><br><br>

*/
$datum=$_GET['datum'];
$tijd1=$_GET['tijd1'];
$tijd2=$_GET['tijd2'];

        $sql = mysql_query("DELETE FROM `" . $pref . "agenda` WHERE `datum`='$datum' AND `tijd1`='$tijd1' AND `tijd2`='$tijd2';") or die(mysql_error());
echo 'Verwijderd';

}
?></td><td><?php
    // Om te kijken of er wel een dag is mee gegeven
if(!isset($_GET['dag']) && !isset($_GET['maand']) && !isset($_GET['jaar']) || !isset($_GET['dag']) || !isset($_GET['maand']) || !isset($_GET['jaar'])) 
{
    echo 'Welkom bij deze agenda, kies een dag wanneer je iets op die dag wilt toevoegen, of wanneer je graag de afspraken wilt lezen die op de dag staan vast-geprikt.';
} 
else 
{
    // stukje veiligheid, kijken op numerieke waardes
    if(!is_numeric($_GET['dag']) || !is_numeric($_GET['maand']) || !is_numeric($_GET['jaar'])) 
    {
        echo '<font color="red">Error: De pagina is oncorrect aangeroepen! Voor uw veiligheid en de onze, krijgt u deze melding, deze melding mag u negeren, aangezien onze systemen in actie zijn getreden.</font><br><br>Welkom bij deze agenda, kies een dag wanneer je iets op die dag wilt toevoegen, of wanneer je graag de afspraken wilt lezen die op de dag staan vast-geprikt.';
    }
    else
    {
        // Is kijken of er toevoegen is mee gegeven
        if(!isset($_GET['a'])) 
        {
            $datum = "".$_GET['dag']."-".$_GET['maand']."-".$_GET['jaar']."";
            echo '<center><b>De afspraken voor datum: '.$datum.'</b><br>';
              if (is('member'))
                  {
                    echo '<a href="?dag='.$_GET['dag'].'&maand='.$_GET['maand'].'&jaar='.$_GET['jaar'].'&a=1">Toevoegen</a>';
                  }
                  echo '</center><p></p><p></p>';
            $sql = mysql_query("SELECT * FROM `" . $pref . "agenda` WHERE datum='$datum'") or die(mysql_error());
            // zijn er afspraken?
            if(mysql_num_rows($sql) == 0) 
            {
                echo '<center><font color="red">Er zijn geen afspraken voor deze dag weggezet.<center><br>';
                if (is('member'))
                  {
                    echo 'Je kan er natuurlijk altijd een <a href="?dag='.$_GET['dag'].'&maand='.$_GET['maand'].'&jaar='.$_GET['jaar'].'&a=1">Toevoegen</a></font>';
                  }
            }
            else
            {
				$ii=0;
                while($data = mysql_fetch_assoc($sql)) {
            ?>
                <b>Omschrijving</b>: <?php echo (function_exists('smile')?smile($data['omschrijving']):$data['omschrijving']); ?><br>
                <b>Tijd</b>: van <?php echo $data['tijd1'];?> tot <?php echo $data['tijd2'];?><br>
                <b>Door</b>: <?php echo $data['door'];?><br>
                <?php
                if(is('mod')) 
                {
                ?>
                  <form method='get'><input type='hidden' name='verwijder' value='xdel'><input type='hidden' name='tijd1' value='<?php echo $data['tijd1']; ?>'><input type='hidden' name='tijd2' value='<?php echo $data['tijd2']; ?>'><input type='hidden' name='datum' value='<?php echo $datum; ?>'><input type='submit' value='verwijder afspraak'></form><br><br>
                <?php
                }
                if ( $ii < mysql_num_rows ( $sql ) )
                 echo '<hr>';
                }
            }
        }
        else 
        {
            // Anders gaan we ff het formulier weergeven wanneer er gevraagd is om toevoegen
            echo '<center><font color="green">Het toevoegen van een afspraak is heel simpel, je vult <u>alles</u> in en je drukt op Verstuur!</font></center>';
            echo '<form action="" method="POST">';
        ?>
        <script>
function toon_table(table_id){

    if(document.getElementById(table_id).style.display == 'none'){
        document.getElementById(table_id).style.display='block'
    } else {
        document.getElementById(table_id).style.display='none'
    }
}
</script>
<fieldset>
<legend>Omschrijving:</legend>
Titel / omschrijving / naam: <input type="text" name="omschrijving" size="50">
</fieldset><br>
<fieldset>
<legend>Datum:</legend>
De datum die u geselecteerd heeft voor de afspraak is <b><?php $datum = "".$_GET['dag']."-".$_GET['maand']."-".$_GET['jaar'].""; echo $datum; ?></b> (<a href="#" onclick="toon_table('datum')">Veranderen</a>)
<table id="datum" style="DISPLAY: none; border-top: 0; font-size: 11px;">
<tr><td><b>Dag</b>: <select name="dag">
<option value="<?php echo $_GET['dag']; ?>" selected>dag</option>
<option value="1">1</option>
<option value="2">2</option>
<option value="3">3</option>
<option value="4">4</option>
<option value="5">5</option>
<option value="6">6</option>
<option value="7">7</option>
<option value="8">8</option>
<option value="9">9</option>
<option value="10">10</option>
<option value="11">11</option>
<option value="12">12</option>
<option value="13">13</option>
<option value="14">14</option>
<option value="15">15</option>
<option value="16">16</option>
<option value="17">17</option>
<option value="18">18</option>
<option value="19">19</option>
<option value="20">20</option>
<option value="21">21</option>
<option value="22">22</option>
<option value="23">23</option>
<option value="24">24</option>
<option value="25">25</option>
<option value="26">26</option>
<option value="27">27</option>
<option value="28">28</option>
<option value="29">29</option>
<option value="30">30</option>
<option value="31">31</option>
</select> 
<b>Maand</b>: <select name="maand">
<option value="<?php echo $_GET['maand']; ?>" selected>Maand</option>
<option value="1">Januari</option>
<option value="2">Februari</option>
<option value="3">Maart</option>
<option value="4">April</option>
<option value="5">Mei</option>
<option value="6">Juni</option>
<option value="7">Juli</option>
<option value="8">Augustus</option>
<option value="9">September</option>
<option value="10">Oktober</option>
<option value="11">November</option>
<option value="12">December</option>
</select>
<b>Jaar</b>: <select name="jaar">
<option value="<?php echo $_GET['jaar']; ?>" selected>Jaar</option>
<option value="2006">2006</option>
<option value="2007">2007</option>
<option value="2008">2008</option>
<option value="2009">2009</option>
<option value="2010">2010</option>
</select></td></tr></table>
</fieldset><br>
<fieldset>
<legend>Tijd:</legend>
<b>Van</b>: <select name="tijd1">
<?php printtijd(); ?>
</select> uur <b>tot</b>:
<select name="tijd2">
<?php printtijd(); ?>
</select> uur</fieldset>
<br>
<fieldset>
<legend>Door:</legend>
Door / uw naam / uw nickname: <input type="hidden" name="door" value="<?php echo $member['realname'];?>"><input type="text" name="xdoor" value="<?php echo $member['realname'];?>" disabled="true" size="50">
</fieldset><br>
<fieldset>
<legend>Toevoegen</legend>
Submit / versturen / toevoegen: <input type="submit" name="submit" value="verstuur!"><br>
Wissen / leegmaken / verwijderen: <input type="reset" name="reset" value="legen">
</fieldset>
<?php 
    // afhandelen
    if(isset($_POST['submit'])) {
        if(empty($_POST)) {
            echo '<fieldset><legend>Fouten:</legend><font color="red">Errror! Je hebt niet alle verplichte waardes ingevuld!</font></fieldset>';
        }

        if($_POST['dag'] == "#" || $_POST['maand'] == "#" || $_POST['jaar'] == "#") {
            $postdatum = "".$_GET['dag']."-".$_GET['maand']."-".$_GET['jaar']."";
        } else {
            $postdatum = "".$_POST['dag']."-".$_POST['maand']."-".$_POST['jaar']."";
        }

        $omschrijving = $_POST['omschrijving'];
        $door = $_POST['door'];
        $tijd1 = $_POST['tijd1'];
        $tijd2 = $_POST['tijd2'];
        $sql = mysql_query("INSERT INTO `" . $pref . "agenda` ( `omschrijving` , `door` , `datum` , `tijd1` , `tijd2` ) VALUES ('$omschrijving', '$door', '$postdatum', '$tijd1', '$tijd2')") or die(mysql_error());
        echo '<font color="green">De afspraak is succesvol toegevoegd.</font>';
}
        }
    }
}
?></td></tr></table>