<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















function overlay($text,$close=true,$scroll=true)
{
 $a  = "<script type=\"text/javascript\">";
 
 $text = preg_replace("#'#","\\'",$text);
 $text = preg_replace("#\r#",null,$text);
 $text = preg_replace("#\n#",null,$text);
	global $conf,$lang;
	$e = $conf['site']['url'] . 'template/admin/images/';
	if (! $close )
	 $x = null;
	Else
 	 $x = "<div style=\"margin:10px;float:right;\"><a id=\'overlink\' href=\'javascript:hideoverlay();\'><img src=\"{$e}js003.png\" border=\"0\"></a></div>";
 $a .= "overlay('{$x}<div style=\"margin:-10px 10px 10px 10px;\"><!--- <img src=\"{$e}js002.png\"> --><h3>&nbsp;&nbsp;&nbsp;{$conf['site']['name']}&nbsp;{$lang['site']['info']}:</h3></div>" .  
 "<br/><div style=\"min-height:115px;margin:0px 10px 0px 10px;\"><center>{$text}</center></div>";
 $a .= "',";
 $a .= (($scroll) ? 'true' : 'false');
 $a .= ");";
 $a .= "</script>";

 return $a;
}

function progressbar ( $h ) {
global $url;
?>
<!-- { Begin Progressbar -->
	<div id="progress-bar" style="background: url('<?php echo $url; ?>template/admin/images/percentage-bg.png') no-repeat left center; width: 316px; height: 20px;">
		<!-- { begin progress level -->
			<div id="progress-level" style="background: url('<?php echo $url; ?>template/admin/images/progress.png') no-repeat left center; width: <?php echo $h; ?>%; height: 20px;">
				<!-- { Fix Empty Space } --><center><?php echo $h; ?>%</center>
			</div>
		<!-- End progress level } -->
	</div>
<!-- End Progressbar } -->
<?php
}
?>