<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















if ( !defined ( 'in_wdgss' ) )
 {
  exit("You`ll Missed This Action");
 }
 if (!defined("lang")) define("lang",$conf['site']['lang']);
 if (!defined("lang")) define("lang",'en');
 
  # {REPLACE}
 
 if ( isset ( $conf['module']['autoload'] ) )
	 {
		 $loadalso = explode("~",$conf['module']['autoloadthose']);
		 for ( $i=0; $i<sizeof($loadalso); $i++ ) 
			 {
				$conf['module']['autoload'][] = $loadalso[$i];
			 }
	 }

 if ( file_exists ( 'modules' ) ) 
  $moddir = 'modules';
 elseif ( file_exists ( '../modules' ) ) 
  $moddir = '../modules';
 else
  exit('Missing Files [f:mod]');
  
 $o = opendir($moddir);
 while ( $d = readdir($o) ) {
  if ( $d != '.' && $d != '..' )
	if ( in_array($d,$conf['module']['autoload']) ) 
	{
	 $conf['module']['list'][] = $d;

		 if ( file_exists ( $moddir . '/' . $d .'/lang/' . lang . '.php' ) )
			{
				include $moddir . '/' . $d .'/lang/' . lang . '.php';
				$l = lang;
			}
		 elseif ( file_exists ( $moddir . '/' . $d .'/lang/en.php' ) )
			{
				include $moddir . '/' . $d .'/lang/en.php';
				$l = 'en';
			}
		 else
			{
				exit("Missing Language File(s) (Ex: en,nl.. Now: ".lang.") For Module {$d}.");
			}
		
	 if ( file_exists ( $moddir . '/' . $d .'/module.php' ) )
	  include $moddir . '/' . $d . '/module.php';
	}
	else
	{
	 $conf['module']['list'][] = $d;
	}
 }
?>