<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















#PID = PROFILE ID
# _GET['PID'];

 if ( isset ( $_GET['id'] ) )
  {
    if ( $_GET['id'] == 'index' )
      {
        unset($_GET['id']);
      }
  }
  
 if ( isset ( $_GET['id'] ) ) #HELPID
  {
   		$a = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}help` WHERE `id` = '".$_GET['id']."' LIMIT 1");
			$b = $conf['database']['db'] -> fetch($a, 'array');
			echo "<a href='{$url}help/index'>Index.</a><br><h1>{$_GET['id']}</h1>" . ( ( isset ( $b [ 0 ] [ 'text' ] ) ? $b[0]['text'] : 'This Article Does Not Exists' ) );
  }
  else
  {

   		$a = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}help`");
			$b = $conf['database']['db'] -> fetch($a, 'array');
			echo "<h1>Help Topics</h1>";
			for($i=0; $i<sizeof($b); $i++)
        {
          if ( (!(preg_match("#(U|u)(P|p)(D|d)(A|a)(T|t)(E|e)\:#", $b[$i]['id'])) Or isset($_GET['upd'])) )
            echo "<a href='{$url}help/{$b[$i]['id']}'>{$b[$i]['id']}</a><br>";
        }
  }
?>