<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################














#$lang['agenda'][''] = ''; 
$lang['agenda'] 			 = array();
$lang['agenda']['WK'] 		 = 'WK';
$lang['agenda']['MO'] 		 = 'MO';
$lang['agenda']['TU'] 		 = 'TU';
$lang['agenda']['WE'] 		 = 'WE';
$lang['agenda']['TH'] 		 = 'TH';
$lang['agenda']['FR'] 		 = 'FR';
$lang['agenda']['SA'] 		 = 'SA';
$lang['agenda']['SU'] 		 = 'SU';

$lang['agenda']['wholeday']  = 'Whole Day';
$lang['agenda']['tot'] 		 = 'To';
$lang['agenda']['title'] 	 = 'Title';
$lang['agenda']['by']        = 'By';
$lang['agenda']['message']   = 'Message';
$lang['agenda']['time']      = 'Time';

$lang['agenda']['sure']      = 'Are You Sure?';
$lang['agenda']['delitem']   = 'Delete Item';

$lang['agenda']['add'] 		 = 'Make Item';
$lang['agenda']['notexists'] = 'No Item Yet';

$lang['agenda']['select']    = 'Select A Date';
$lang['agenda']['gotoday']   = 'Go To Today';
?>