<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################














#$lang['agenda'][''] = ''; 
$lang['agenda'] 			 = array();
$lang['agenda']['WK'] 		 = 'WK';
$lang['agenda']['MO'] 		 = 'MA';
$lang['agenda']['TU'] 		 = 'DI';
$lang['agenda']['WE'] 		 = 'WO';
$lang['agenda']['TH'] 		 = 'DO';
$lang['agenda']['FR'] 		 = 'VR';
$lang['agenda']['SA'] 		 = 'ZA';
$lang['agenda']['SU'] 		 = 'ZO';

$lang['agenda']['wholeday']  = 'Hele Dag';
$lang['agenda']['tot'] 		 = 'Tot';
$lang['agenda']['title'] 	 = 'titel';
$lang['agenda']['by']        = 'Door';
$lang['agenda']['message']   = 'Bericht';
$lang['agenda']['time']      = 'Tijd';

$lang['agenda']['sure']      = 'Weet U Het Zeker?';
$lang['agenda']['delitem']   = 'Verwijder Item';

$lang['agenda']['add'] 		 = 'Maak Item';
$lang['agenda']['notexists'] = 'Nog Geen Afspraak';

$lang['agenda']['select']    = 'Selecteer Een Item';
$lang['agenda']['gotoday']   = 'Naar Vandaag';
?>