<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















function a ( $x )
{
	global $conf;
	#template/default/
		if ( file_exists ( './template/smilies/msn_' . $x . '.png' ) )
		{
			$f = $conf['site']['url'] . 'template/smilies/msn_' . $x . '.png';
		}
		elseif ( file_exists ( './template/smilies/msn_' . $x . '.gif' ) )
		{
			$f = $conf['site']['url'] . 'template/smilies/msn_' . $x . '.gif';
		}
		else { $f = '\' alt=\'Not Found...'; }
	return '<img src=\'' . $f . '\'>';
}

function s ( $s )
{
	return '#\(' . $s . '\)#';
}

function smile ( $text ) {
$smiles=array(
	s('A') 		=> a('angel'),
	'#\:@#'		=> a('angry'),
	'#\:-\[#'	=> a('bat'),
	s('B') 		=> a('beer'),
	s('Z') 		=> a('boy'),
	s('brb') 	=> a('brb'),
	s('U') 		=> a('brheart'),
	s('\^')		=> a('cake'),
	s('AU')     => a('car'),
	s('@')		=> a('cat'),
	s('MP')		=> a('cellphone'),
	s('L') 		=> a('heart'),
	s('\:\)')     => a('smiley')
);

 return replace($text,$smiles);
}

if ( isset ( $_GET['calasics'] ) )
{

$c = $conf['database']['db'];

$d = $c -> query ( "SELECT `username`,`birthday` FROM `{$conf['database']['pref']}users`;" ) ;
$n = $c -> num ( $d, 'row' ) ;
$d = $c -> fetch ( $d, 'array' ) ;
$agenda = array ( ) ;
$ag     = array ( ) ;

# id 	omschrijving 	door 	datum 	tijd1 	tijd2
for ( $i=0; $i<sizeof($d); $i++ )
 {
  preg_match("#(.*)-(.*)-(.*)#", $d[$i]['birthday'], $match);
  $x = array (
						'Verjaardag Van: ' . $d[$i]['username'],
						"{$d[$i]['username']} Woord " . age($d[$i]['birthday']) . ".<br>Nog Vele Jaren <br>Met Vriendelijk Groeten,<br>Team {$conf['site']['name']}",
						( $match [ 3 ] = ( ( ( $match [ 3 ] < 10 ) && ( strlen ( $match [ 3 ] ) == 1 ) ) ? '0' . $match [ 3 ] : $match [ 3 ] ) ),
						( $match [ 2 ] = ( ( ( $match [ 2 ] < 10 ) && ( strlen ( $match [ 2 ] ) == 1 ) ) ? '0' . $match [ 2 ] : $match [ 2 ] ) ),
						date("Y"),
						'Team ' . $conf['site']['name'],
						'00:00',
						'00:00'
					);
	$ag[] = $x; #FIX: $match[1]=date(y);
 }
$d = $c -> query ( "SELECT * FROM `{$conf['database']['pref']}agenda`;" ) ;
$n = $c -> num ( $d, 'row' ) ;
$d = $c -> fetch ( $d, 'array' ) ;

# id 	omschrijving 	door 	datum 	tijd1 	tijd2
for ( $i=0; $i<sizeof($d); $i++ )
 {
		$oms = preg_replace("#<(b|B)(r|R|r /|R /)>#",null,$d[$i]['omschrijving']);
		preg_match("#(.*)-(.*)-(.*)#", $d[$i]['datum'], $match);
		$x = array(
			inkorten($oms, 32),
			$d[$i]['omschrijving'],
			( $match [ 1 ] = ( ( ( $match [ 1 ] < 10) && ( strlen ( $match [ 1 ] ) == 1 ) ) ? '0' . $match [ 1 ] : $match [ 1 ] ) ),
			( $match [ 2 ] = ( ( ( $match [ 2 ] < 10) && ( strlen ( $match [ 2 ] ) == 1 ) ) ? '0' . $match [ 2 ] : $match [ 2 ] ) ),
			( $match [ 3 ] = ( ( ( $match [ 3 ] < 10) && ( strlen ( $match [ 3 ] ) == 1 ) ) ? '0' . $match [ 3 ] : $match [ 3 ] ) ),
			$d[$i]['door'],
			$d[$i]['tijd1'],
			$d[$i]['tijd2']
		);
	$ag[] = $x;
 }

$cfg 		  	= array();
$cfg['datum'] 	= date("d/m/Y"); 
$cfg['day'] 	= date("d"); # Day (1-31)

$cfg['week'] 	= date("W"); # Week Number
$cfg['doy']     = date("z"); # Day Of Year
$cfg['dim']     = @cal_days_in_month(CAL_GREGORIAN,$cfg['month'],$cfg['year']) + 1; #Days In Month

//pereienete_ere(e$eaege)e;

/*
    [0] => Array
        (
            [0] => Verjaardag Van: Wes
            [1] => Wes Woord 20 Jaar.<br>Nog Vele Jaren <br>Met Vriendelijk Groeten,<br>Team WesDeGroot Site System
            [2] => 03
            [3] => 08
            [4] => 2011
            [5] => Team WesDeGroot Site System
            [6] => 00:00
            [7] => 00:00
        )
*/

$cal=new ical('WDGSS');
///             TITLE DESC   DATE(Ymd)  TIME(His)   DEND(Ymd)

for($i=0; $i<sizeof($ag); $i++)
  {
    $ag[$i][1] = preg_replace ( "/\<br>/",  "\\n",   $ag[$i][1]);
    $ag[$i][6] = preg_replace ( "/00\:00/", "12:00", $ag[$i][6]);
    $ag[$i][6] = preg_replace ( "/\:/",     null,    $ag[$i][6]);
    $cal->addevent($ag[$i][0],$ag[$i][1],$ag[$i][4].$ag[$i][3].$ag[$i][2],$ag[$i][6].'00', $ag[$i][4].$ag[$i][3].$ag[$i][2]);
  }

$cal->send();


exit;
}

?>