<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















 // login
 @session_start();

if ( !defined ( "login" ) ) 
{
 if ( isset ( $_POST['username'] ) && isset ( $_POST['password'] ) )
 {
	$a = $conf['database']['db'] -> query("SELECT `id`,`username`,`password` FROM `{$conf['database']['pref']}users` WHERE `username` = '{$_POST['username']}' LIMIT 1");
	$a = $conf['database']['db'] -> fetch($a, 'array');

	if ( isset ( $a[0]['password'] ) )
	{
		if ( $a[0]['password'] == md55 ( $_POST['password'] ) ) 
		{
			$_SESSION['login']     = $_POST['username'];
			$_SESSION['hijack']    = getip(true); //SESSION HIJACKING
			echo sprintf($lang['login']['loggedin'],$_POST['username']);
			if ( isset ( $_SESSION['lasturl'] ) )
			 {
				renew(0,$_SESSION['lasturl']);
			 }
			else
			 {
				renew(2,'home.pag');
			 }
 		}
 		else
 		{
			echo sprintf($lang['login']['wrongpass']); 		
 		}
	}
	else
	{
	 echo sprintf($lang['login']['notexists'],$_POST['username']);
	}
  }
 
?>
<form method='post' action='<?php echo $conf['site']['url']; ?>login.pag'>
<table>
	<tr>
		<td>
			<?php echo $lang['register']['username']; ?>
		</td>
		<td>
			<input type='text' name='username'>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $lang['register']['password']; ?>
		</td>
		<td>
			<input type='password' name='password'>
		</td>
	</tr>
</table>
<table><tr><td><input type='submit' value='<?php echo $lang['site']['login']; ?>'>
</form></td>
<td>
<form method='get' action='<?php echo $url; ?>page/register'><input type='submit' value='<?php echo $lang['site']['register']; ?>'></form>
</td></tr></table>
<?php
}else{
?><form method='post' action='<?php echo $conf['site']['url']; ?>login.pag?user_logout=true'>
<input type='submit' value='<?php echo $lang['register']['logout']; ?>'>
</form><?php } ?>