<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















 # {REP}
					
define("MAX_SIZE", 1);
define("MIN_SIZE", 2);
define("EXACT_SIZE", 3);

function UploadImage($file, $to_url, $allowed_types = NULL, $allowed_ext = NULL, $sizes = NULL)
{
    if(is_uploaded_file($file["tmp_name"]))
    {                                                                
        list($x, $y, $image_type) = getimagesize($file["tmp_name"]);
        list($gx, $gy, $ctype) = $sizes;
        $split_name = explode(".", $file["name"]);        
        $file_name = $file["name"];            
        if((($sizes == NULL) || (($ctype == MAX_SIZE) && (($x <= $gx) && ($y <= $gy))) || (($ctype == MIN_SIZE) && (($x >= $gx) && ($y >= $gy))) || (($ctype == EXACT_SIZE) && (($x == $gx) && ($y == $gy)))) && (($allowed_types == NULL) || (array_search($image_type, $allowed_types, true) !== false)) && (($allowed_ext == NULL) || (array_search(strtolower($split_name[count($split_name) - 1]), $allowed_ext) !== false)))
        {    
            $pattern = "1234567890abcdefghijklmnopqrstuvwxyz";
            while(file_exists($to_url . $file_name))
            {
                $split_name[0] = $split_name[0] . $pattern{ rand(0, 35) };    
                $file_name = implode(".", $split_name);
            }
            move_uploaded_file($file["tmp_name"], ($to_url . $file_name));
            return $file_name;
        }
    }
    return false;    
}
 
 if($_SERVER["REQUEST_METHOD"] == "POST" && isset($_FILES['objUpload']))
{

				if ( isset ( $_SESSION['login'] ) )
					{ 
					if ( preg_match ( "#admin/module/profile#", $_SERVER['REQUEST_URI'] ) && isset($_GET['id']) ) 
						{
							$user = $_GET['id'];
						}
					else
						{
							$user = $_SESSION['login']; 
						}
					}
				else
					{ ga($conf['site']['url'] . "login.pag"); }

    $sizes = array(60, 40, MIN_SIZE); // array(x, y, MIN_SIZE|MAX_SIZE|EXACT_SIZE)
    $allowed_types = array(IMAGETYPE_GIF, IMAGETYPE_JPEG, IMAGETYPE_PNG); // array(types van: http://nl3.php.net/manual/nl/function.exif-imagetype.php)
    $allowed_ext = array("jpg", "png", "gif"); // array(ext1, ext2, ext3)
    $path = "data/avatar/"; // Str: waar die geupload moet worden.
    $global = $_FILES["objUpload"]; // De global.
    if($filename = UploadImage($global, $path, $allowed_types, $allowed_ext, $sizes))
    {

$sqla = "
	UPDATE 
		`{$conf['database']['pref']}users` 
	SET 
		`avatar`	=	'" . ( secure ( $filename ) ) . "'
	WHERE
		`username`	=	'{$user}' OR
		`id`		=	'{$user}' OR
		`realname`	=	'{$user}'
	LIMIT 1;";

	$s = $conf['database']['db'] -> query($sqla);
        echo ("<img src=\"" . $path . $filename . "\"  width='100' height='100' alt=\"" . $path . $filename . "\" />");   
    }
    else
    {    
        echo "ERR UPLOAD";
    }    
}


function usr_edit($WHO='DEF')
	{
	global $conf,$url,$lang;
		#USEREDIT
		if ( $WHO == 'DEF' ) 
			{ 
				if ( defined ( 'login' ) )
					{ $user=login;
						$sql = "SELECT 
 *
 FROM `{$conf['database']['pref']}users` 
 WHERE
 `username`='{$user}' OR
 `id`='{$user}' OR
 `realname`='{$user}'
 LIMIT 1;";
					}
				else
					{
						ga($conf['site']['url'] . "login.pag");	
					}
			}
		else
			{
				if ( defined ( 'login' ) && is ( 'mod' ) )
					{ $user=$WHO;
						$sql = "SELECT 
 *
 FROM `{$conf['database']['pref']}users` 
 WHERE
 `username`='{$user}' OR
 `id`='{$user}' OR
 `realname`='{$user}'
 LIMIT 1;";
					}
				else
					{
						ga($conf['site']['url'] . "login.pag");	
					}
			}

if ( 
	isset ( $_POST [ 'hideprofile' ] )  &&
	isset ( $_POST [ 'realname' ] ) 	&&
	isset ( $_POST [ 'hiderealname' ] ) &&
	isset ( $_POST [ 'email' ] ) 		&&
	isset ( $_POST [ 'hideemail' ] ) 	&&
	isset ( $_POST [ 'website' ] ) 		&&
	isset ( $_POST [ 'birthday' ] ) 	&&
	isset ( $_POST [ 'hidebirthday' ] ) &&
	isset ( $_POST [ 'theme' ] ) &&
	isset ( $_POST [ 'text' ] )	
   )
{
$sqlt = "
	UPDATE 
		`{$conf['database']['pref']}users` 
	SET 
		`hideprofile`	=	'" . ( secure ( $_POST [ 'hideprofile'  ] ) ) . "',
		`realname`		=	'" . ( secure ( $_POST [ 'realname'	    ] ) ) . "',
		`hiderealname`	=	'" . ( secure ( $_POST [ 'hiderealname' ] ) ) . "',
		`email`			=	'" . ( secure ( $_POST [ 'email'        ] ) ) . "',
		`hideemail`		=	'" . ( secure ( $_POST [ 'hideemail'	] ) ) . "',
		`website`		=	'" . ( secure ( $_POST [ 'website'      ] ) ) . "',
		`birthday`		=	'" . ( secure ( $_POST [ 'birthday'     ] ) ) . "',
		`hidebirthday`	=	'" . ( secure ( $_POST [ 'hidebirthday' ] ) ) . "',
		`theme`			=	'" . ( secure ( $_POST [ 'theme' ] ) ) . "',
		`text`			=	'" . ( secure ( $_POST [ 'text' ] ) ) . "'
WHERE
	`username`	=	'{$user}' OR
	`id`		=	'{$user}' OR
	`realname`	=	'{$user}'
LIMIT 1;";
$s = $conf['database']['db'] -> query($sqlt);
            $go=substr($conf['site']['url'],0,strlen($conf['site']['url'])-1) . $_SERVER['REQUEST_URI'];
            echo ga($go);
			echo renew('3',$go,true);
if ( $s ) 
 echo overlay("Sucess " . mysql_error());
Else 
 echo overlay("ERROR: " . mysql_error());
}

if ( isset ( $_POST['status'] ) && is ( 'admin' ) )
 {
			$sqlt = "
			UPDATE 
				`{$conf['database']['pref']}users` 
			SET 
				`status`	=	'" . ( secure ( $_POST [ 'status' ] ) ) . "'
			WHERE
				`username`	=	'{$user}' OR
				`id`		=	'{$user}' OR
				`realname`	=	'{$user}'
			LIMIT 1;";
			echo renew('3',$conf['site']['url'] . $_SERVER['REQUEST_URI'],true);

			$s = $conf['database']['db'] -> query($sqlt);
			if ( $s ) 
			 echo overlay("Sucess 4 {$user}" . mysql_error());
			Else 
			 echo overlay("ERROR: " . mysql_error());
 }
 
if ( 
	isset ( $_POST['password1'] )  &&
	isset ( $_POST['password2'] ) 
   )
{
	if ( $_POST['password1'] == $_POST['password2'] )
		{
			$sqlt = "
			UPDATE 
				`{$conf['database']['pref']}users` 
			SET 
				`password`	=	'" . ( md55 ( secure ( $_POST [ 'text' ] ) ) ) . "'
			WHERE
				`username`	=	'{$user}' OR
				`id`		=	'{$user}' OR
				`realname`	=	'{$user}'
			LIMIT 1;";

			echo renew('3',$conf['site']['url'] . $_SERVER['REQUEST_URI'],true);

			$s = $conf['database']['db'] -> query($sqlt);
			if ( $s ) 
			 echo overlay("Sucess " . mysql_error());
			Else 
			 echo overlay("ERROR: " . mysql_error());
		}
	else
		{
			echo $lang['register']['passnotmatch'];
		}
}


// $sql :P
$s = $conf['database']['db'] -> query($sql);
$s = @$conf['database']['db'] -> fetch($s,'array');

				$themes = array();
				$o = opendir('template');
				while ( ( $f = readdir ( $o ) ) !== false ) 
				{
				 if ( $f != '.' && $f != '..' && is_dir("template/" . $f) && $f != 'admin' && $f != 'smilies' )
				  $themes[] = '<option name=\'' . $f .'\'' . (($s[0]['theme']==$f)?' Selected':null) . '>' . $f . '</option>';
				}
				sort($themes);
				$themes = implode('',$themes);


$doit	=	array	(
	"hideprofile"  => array	(	$s[0]['hideprofile'],	'yn'		),
	"realname"     => array	(	$s[0]['realname'],		'text'		),
	"hiderealname" => array	(	$s[0]['hiderealname'],	'yn'		),
	"email"        => array	(	$s[0]['email'],			'text'		),
	"hideemail"    => array	(	$s[0]['hideemail'],		'yn'		),
	"website"      => array	(	$s[0]['website'],		'text'		),
	"birthday"     => array	(	$s[0]['birthday'],		'text'		),
	"hidebirthday" => array	(	$s[0]['hidebirthday'],	'yn'		),
    "theme"        => array (   $themes,				'select'    ),
 	"text"         => array	(	$s[0]['text'],			'textarea'	)
);
echo "<form method=\"POST\" enctype=\"multipart/form-data\" action=\"{$_SERVER['REQUEST_URI']}\"><input type=\"file\" name=\"objUpload\" /><input type=\"submit\" name=\"objSubmit\" value=\"Upload\" /></form>";
echo "<form method='post' action='{$_SERVER['REQUEST_URI']}'><table>";
foreach($doit As $what => $array )
{
 switch ( $array[1] )
 {
  case 'yn':
   $My="\r\n<select name='{$what}'>\r\n <option name='0' value='0'".(($array[0]==0)?' selected':null).">{$lang['register']['no']}</option>\r\n <option name='1' value='1'".(($array[0]==1)?' selected':null).">{$lang['register']['yes']}</option>\r\n</select>";
  break;

  case 'text':
   $My="<input type='text' name='{$what}' value='{$array[0]}'>"; 
  break;
  
  case 'textarea':
   $My = "<textarea id='{$what}' name='{$what}' rows='10' cols='50'>{$array[0]}</textarea>";
   ob_start();
   wysiwyg($what);
   $X=ob_get_contents();
   ob_end_clean();
   $My .= $X;
  break;

  case 'select': 
   $My = "<select name='{$what}'>" . $array[0] . "</select>";
  break;
   
  default:
   $My=null;
  break;
 }
echo "\r\n<tr>\r\n<td>" . $lang['register'][$what] . "</td>\r\n<td>$My</td>\r\n</tr>\r\n";
}
echo "</table><input type='submit'></form>";
//$WHO='DEF'
echo "<form method='post' action='{$_SERVER['REQUEST_URI']}'>";
 if ( is ( 'admin' ) ) {
?>
<table>
	<tr>
		<td>
			Status
		</td>
		
		<td>
			<select name='status'>
				 <option value='0' name='0'<?php if ($s[0]['status'] == 0) { echo " Selected=\"Selected\""; } ?>>
					Banned
				 </option>
				 
				 <option value='1' name='1'<?php if ($s[0]['status'] == 1) { echo " Selected=\"Selected\""; } ?>>
					Normal User
				 </option>
				 
				 <option value='2' name='2'<?php if ($s[0]['status'] == 2) { echo " Selected=\"Selected\""; } ?>>
					Vip
				 </option>
				 
				 <option value='3' name='3'<?php if ($s[0]['status'] == 3) { echo " Selected=\"Selected\""; } ?>>
					Moderator
				 </option>

				 <option value='4' name='4'<?php if ($s[0]['status'] == 4) { echo " Selected=\"Selected\""; } ?>>
					Admin
				 </option>
			</select>
		</td>
	</tr>
</table>
<input type='submit'><br>
<?php
}
echo "</form><form method='post' action='{$_SERVER['REQUEST_URI']}'>";
?>
<table>
		<tr>
			<td>
				<?php echo $lang['register']['password']; ?><br>
				<?php echo $lang['register']['confirm']; ?>
			</td>
			<td>
				<input type='password' name='password'><br>
				<input type='password' name='confirm'><br>
				<input type='submit'>
			</td>
		</tr>

</table>
</form>
<?php
	}

 ///Hier Komt Het Gastenboek
function usr_error($over='NO AVATAR')
	{
		global $conf;
		draw_email($conf,$over);
	}

function user_avatar ( $coee, $user=null )
{
 global $conf;
if($user==null)
 $user = (isset($_SESSION['avatar'])?$_SESSION['avatar']:'NE');
 $s = $conf['database']['db'] -> query("
 SELECT 
 `avatar` 
 FROM `{$conf['database']['pref']}users` 
 WHERE
 `username`='{$user}' OR
 `id`='{$user}' OR
 `realname`='{$user}'
 LIMIT 1;
 ");
 $n = @$conf['database']['db'] -> num($s,'rows');
 $s = @$conf['database']['db'] -> fetch($s,'array');
 if ( $n != 0 )
 {
	 if ( file_exists ( "data/avatar/" . $s[0]['avatar'] ) )
	 {
		$ext = explode(".",$s[0]['avatar']);
		$ext = $ext[sizeof($ext)-1];

		switch ( strtolower ( $ext ) )
		{
			case 'jpg':
			case 'jpeg':
				header("content-type: image/jpeg");
				exit(file_get_contents("data/avatar/" . $s[0]['avatar']));
			break;

			case 'png':
				header("content-type: image/png");
				exit(file_get_contents("data/avatar/" . $s[0]['avatar']));
			break;

			case 'gif':
				header("content-type: image/gif");
				exit(file_get_contents("data/avatar/" . $s[0]['avatar']));
			break;

			case 'bmp':
				header("content-type: image/bmp");
				exit(file_get_contents("data/avatar/" . $s[0]['avatar']));
			break;

			default:
				usr_error("Unknown Format."); 
			break;
		}
	 }
	 else
	 {
	  usr_error();
	 }
 }
 else
 {
  usr_error();
 } 
}
?>