<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















 function _adminchat() {
  global $conf,$lang;
  $r = null;
  
   if ( isset ( $_POST['url'] ) && isset ( $_POST['oldurl'] ) )
    {
     $_POST['url'] = preg_replace("/=/","_is_",$_POST['url']);
    /*http://chat.wesdegrootprojects.nl/?chan=wdgss&server=irc.loungechat.net&nick=Wdgss%*/
     $conf['database']['db'] -> query("UPDATE `{$conf['database']['pref']}config` SET `config`='chat:url={$_POST['url']}' WHERE `config`='chat:url={$_POST['oldurl']}'; ");
    }
    
    $a = $conf['database']['db'] -> query("SELECT `config` FROM `{$conf['database']['pref']}config` WHERE `config` LIKE '%chat:url%'");
    $a = $conf['database']['db'] -> fetch( $a, 'array' );
    preg_match_all("#chat\:url=(.*)#", $a[0]['config'], $ret);
    $ret[1][0] = preg_replace("/_is_/","=",$ret[1][0]);
    # => $ret[1][0]
    $r .= "<form method='post' action='{$conf['site']['url']}admin.pag?act=modules&mod=chat'>Url: <input type='hidden' name='oldurl' value='{$ret[1][0]}'> <input type='text' name='url' value='{$ret[1][0]}'> <input type='submit'> </form>";
  return $r;
 }
?>