<b style="font-size:15px">Let op! Dit is een JAVA webchat. Zorg ervoor dat je deze java applicatie NIET blokkeert wanneer JAVA het met een 'schermpje' aan je vraagt.</b><br/><br/>	
<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















$_GET['chan']="nachtlounge";
$aj=false;
if(!isset($_GET['nick']))
{
echo "<form method='get'><p>Nickname:<br><input type='text' name='nick'><br>
Wachtwoord (Optioneel, niet verplicht):<br> <input name='pwd' type='password'></p>";
foreach ( $_GET As $s1 => $s2 )
{
 echo "<input type='hidden' name='" . $s1 . "' value='" . $s2 . "'>";
}
echo "<p><input type='submit' value='Chatten'></p>";
}
else
{

 $chans = ( isset ( $_GET['chans'] ) ? $_GET['chans'] : 'nachtlounge' );
 $chans = ( isset ( $_GET['chan'] )  ? $_GET['chan']  : 'nachtlounge' );

 $chans = implode(",#",explode(",",$chans));
 $chans = implode(",#",explode("|",$chans));
 
echo '<applet code=\'IRCApplet.class\' archive="irc.jar,pixx.jar" width=\'99%\' height=\'500\'>
<param name="CABINETS" value="irc.cab,securedirc-unsigned.cab,pixx.cab">
 
<param name="nick" value="'.$_GET['nick'].'">
<param name="alternatenick" value="'.$_GET['nick'].'_2">
<param name="alternatenick2" value="Guest???">
<param name="name" value="WDGSS_WEB_Chat">
<param name="port" value="6667">
<param name="host" value="irc.loungechat.net">
<!-- param name="userid" value="WDGSSWebChat" -->
<param name="autorejoin" value="true">
<param name="command1" value="/join #' . $chans . '">
<param name="gui" value="pixx">
<param name="quitmessage" value="WDGSS webchat http://www.wocnl.nl!">
<param name="asl" value="true">
<param name="useinfo" value="true">
 
<param name="style:bitmapsmileys" value="true">
<param name="style:smiley1" value=":) img/sourire.gif">
<param name="style:smiley2" value=":-) img/sourire.gif">
<param name="style:smiley3" value=":-D img/content.gif">
<param name="style:smiley4" value=":d img/content.gif">
<param name="style:smiley5" value=":-O img/OH-2.gif">
<param name="style:smiley6" value=":o img/OH-2.gif">
<param name="style:smiley7" value=":-P img/langue.gif">
<param name="style:smiley8" value=":p img/langue.gif">
<param name="style:smiley9" value=";-) img/clin-oeuil.gif">
<param name="style:smiley10" value=";) img/clin-oeuil.gif">
<param name="style:smiley11" value=":-( img/triste.gif">
<param name="style:smiley12" value=":( img/triste.gif">
<param name="style:smiley13" value=":-| img/pleure.gif">
<param name="style:smiley14" value=":| img/pleure.gif">
<param name="style:smiley15" value=":\ img/pleure.gif">
<param name="style:smiley15" value=":-\ img/pleure.gif">
<param name="style:smiley16" value=":$ img/rouge.gif">
<param name="style:smiley17" value=":-$ img/rouge.gif">
<param name="style:smiley18" value="(H) img/cool.gif">
<param name="style:smiley19" value="(h) img/cool.gif">
<param name="style:smiley20" value=":-@ img/enerve1.gif">
<param name="style:smiley21" value=":@ img/enerve2.gif">
<param name="style:smiley22" value=":-S img/roll-eyes.gif">
<param name="style:smiley23" value=":s img/roll-eyes.gif">
<param name="style:smiley24" value="(6) img/evil.gif">
<param name="style:smiley25" value=":LOL: img/lol.gif">
<param name="style:smiley26" value=":O img/OH-1.gif">
<param name="style:smiley27" value=":D img/content.gif">
<param name="style:smiley28" value=":S img/roll-eyes.gif">
<param name="style:smiley29" value="(A) img/ange.gif">
<param name="style:smiley30" value="(a) img/ange.gif">
<param name="style:smiley38" value=":P img/langue.gif">

<param name="style:backgroundimage" value="true">

<param name="style:sourcefontrule1" value="all all Tahoma 12">

<param name="style:floatingasl" value="true">

<param name="pixx:timestamp" value="true">
<param name="pixx:highlight" value="true">
<param name="pixx:highlightnick" value="true">
<param name="pixx:nickfield" value="true">
<param name="pixx:styleselector" value="true">
<param name="pixx:setfontonstyle" value="true">
 
<param name="language" value="english">
      
<param name="pixx:highlightwords" value="'.$_GET['nick'].' '.$_GET['nick'].'_2">
<param name="pixx:showconnect" value="false">
<param name="pixx:showchanlist" value="true">
<param name="pixx:showabout" value="false">
<param name="pixx:showhelp" value="false">
<param name="pixx:helppage" value="?fay=true">
<param name="sbox:showtaskbar" value="true">
 
 
<param name="pixx:popupmenustring1" value="Whois">
<param name="pixx:popupmenustring2" value="Kick + Ban">
 
<param name="pixx:popupmenucommand1_1" value="/whois %1">
<param name="pixx:popupmenucommand2_1" value="/mode %2 -o %1">
<param name="pixx:popupmenucommand2_2" value="/mode %2 +b %1">
<param name="pixx:popupmenucommand2_3" value="/kick %2 %1">
 
<param name="pixx:timestamp" value="true">

<param name="pixx:color1" value="222222">
<param name="pixx:color2" value="CCCCCC">
<param name="pixx:color3" value="3AFFFF">
<param name="pixx:color4" value="CCCCCC">
<param name="pixx:color5" value="3AFFFF">
<param name="pixx:color6" value="CCCCCC">
<param name="pixx:color7" value="3AFFFF">
<param name="pixx:color8" value="CCCCCC">
<param name="pixx:color9" value="3AFFFF">
<param name="pixx:color10" value="FFFFFF">
<param name="pixx:color11" value="3AFFFF">
<param name="pixx:color12" value="3AFFFF">
<param name="pixx:color13" value="CCCCCC">
<param name="pixx:color14" value="3AFFFF">
<param name="pixx:color15" value="FFFFFF">
<param name="style:sourcefontrule1" value="all all Tahoma 12">
 
 
' ;

if ( isset ( $_GET [ 'leave' ] ) )
 echo '<param name="Command3" value="/part #' . $_GET [ 'leave' ] . ' Channel not allowed on this chat">';

if ( isset ( $_GET [ 'pwd' ] ) )
 echo '<param name="Command2" value="/msg NickServ IDENTIFY ' . $_GET [ 'pwd' ] . '">'; 
 
echo 'Your web browser cannot use this Java Chat interface.
<br>Please upgrade your web browser with <a href="http://www.java.com">Java</a>
or allow the active x component
<hr />
U heeft geen java geinstaleerd, installeer deze op <a href="http://www.java.com">Java</a>
<Br />. Het kan ook zijn dat het active x component geen rechten heeft.
</applet>' . "<br>";
}
?>