<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















#dutch By WesDeGroot

	$lang = array();
	
	# Guestbook related
	$lang['guestbook']['name']         = 'naam';
	$lang['guestbook']['email']        = 'email adres';
	$lang['guestbook']['text']         = 'bericht';
	$lang['guestbook']['captcha']      = 'type dit over';
	$lang['guestbook']['messagesend']  = 'Bericht Is Geplaatst';
	$lang['guestbook']['messagenot']   = 'Bericht Is <u><b>NIET</b></u> Geplaatst</div>';
	$lang['guestbook']['fakeemail']    = 'Email Adres Klopt <u><b>NIET</b></u>';
	$lang['guestbook']['wrongcaptcha'] = 'De Ingevulde Captcha Code Was Niet Goed!';
	$lang['guestbook']['module']       = 'Gastenboek';
	$lang['guestbook']['emailshow']    = 'Laat Email Adres Zien: ';
	$lang['guestbook']['true']         = 'Ja';
	$lang['guestbook']['false']        = 'Neen';
	$lang['guestbook']['save']         = 'Opslaan';
	$lang['guestbook']['edit']         = 'Bewerk';
	$lang['guestbook']['del']		   = 'Verwijder';
	$lang['guestbook']['dele']		   = 'Weet U Zeker Dat U Post Met ID \\\'\\\'%s\\\'\\\' Wilt Verwijderen?';
	$lang['guestbook']['deleted']	   = 'Post Met ID <b><u>%s</u></b> Verwijderd';
	$lang['guestbook']['notdeleted']   = 'Post Met ID <b><u>%s</u></b> Kon <u>niet</u> Verwijderd';
	
	# News related
	$lang['news']['module']            = 'Nieuws';
	$lang['news']['by']                = 'Door:';
	$lang['news']['editedpage']		   = 'Nieuws Pagina Bewerkt';
	$lang['news']['noteditedpage']     = 'Nieuws Pagina Niet Bewerkt';
	$lang['news']['title']			   = 'Titel';
	$lang['news']['content']		   = 'Inhoud';
	$lang['news']['save']			   = 'Opslaan';
	$lang['news']['edit']			   = 'Bewerk';
	$lang['news']['createdpage']	   = 'Nieuws Pagina Gemaakt';
	$lang['news']['notcreatedpage']    = 'Nieuws Pagina Niet Gemaakt';
	$lang['news']['deletedpage']	   = 'Nieuws Pagina Verwijderd';
	$lang['news']['notdeletedpage']    = 'Nieuws Pagina Niet Verwijderd';
	$lang['news']['del']			   = 'Verwijderen';
	$lang['news']['suredelpage']	   = 'Weet U Zeker Dat U Nieuws Pagina \\\'\\\'%s\\\'\\\' Wilt Verwijderen?';
	$lang['news']['newpage']           = 'Nieuw Nieuws Bericht';
	
	# Site related
    $lang['site']['invoice']           = 'Factuur';
	$lang['site']['guestbook']         = 'Gastenboek';
	$lang['site']['seturl']			   = 'Stel Url %s In';
	$lang['site']['setlink']		   = 'Stel Link %s In';
	$lang['site']['profile']           = 'Profiel';
	$lang['site']['login']             = 'Inloggen';
	$lang['site']['news']              = 'Nieuws';
	$lang['site']['register']          = 'Registreer';
	$lang['site']['username']		   = 'Gebruikersnaam';
	$lang['site']['password']		   = 'Wachtwoord';
	$lang['site']['info']			   = 'Mededeling';
	$lang['site']['photobook']         = 'Fotoboek';

	# Error related
	$lang['site']['error']['404']      = '<h1>Fout!</h1>Pagina: %s Niet Gevonden';
	$lang['site']['error']['403']      = '<h1>Fout!</h1>Geen Rechten Om<br>Pagina: %s Te Zien!';
	
	#Age Definitions
	$lang['age']['notborn']			   = 'Nog Niet Geboren';
	$lang['age']['borntoday']	       = 'Vandaag Geboren';
	$lang['age']['today']              = 'Vandaag %s Jaar Gewoorden';
	$lang['age']['year']               = 'Jaar';
	
	#Agenda
	$lang['agenda']['months']     	   = array( 1 => 'Januari', 2 => 'Februari', 3 => 'Maart', 4 => 'April', 5 => 'Mei', 6 => 'Juni', 7 => 'Juli', 8 => 'Augustus', 9 => 'September', 10 => 'Oktober', 11 => 'November', 12 => 'December' );
	$lang['agenda']['first']           = array('M','D','W','D','V','Z','Z'); //maandag, dinsdag, woensdag, donderdag, vrijdag, zaterdag, zondag
	$lang['agenda']['weekdays']  	   = array('maandag','dinsdag','woensdag','donderdag','vrijdag','zaterdag','zondag');
	$lang['agenda']['welcome']   	   = 'Welkom bij deze agenda, kies een dag wanneer je iets op die dag wilt toevoegen, of wanneer je graag de afspraken wilt lezen die op de dag staan vast-geprikt.';
	$lang['agenda']['siteerror'] 	   = 'Error: De pagina is oncorrect aangeroepen! Voor uw veiligheid en de onze, krijgt u deze melding, deze melding mag u negeren, aangezien onze systemen in actie zijn getreden.</font><br><br>Welkom bij deze agenda, kies een dag wanneer je iets op die dag wilt toevoegen, of wanneer je graag de afspraken wilt lezen die op de dag staan vast-geprikt.';
	$lang['agenda']['prikked']	 	   = 'De afspraken voor datum';
	$lang['agenda']['add']		 	   = 'Toevoegen';
	$lang['agenda']['noo']       	   = 'Er zijn geen afspraken voor deze dag weggezet.';
	$lang['agenda']['_add']		 	   = 'Je kan er natuurlijk altijd een';
	$lang['agenda']['delete']    	   = 'verwijder afspraak';
	$lang['agenda']['deleted']   	   = 'Verwijderd';
	$lang['agenda']['description']	   = 'Omschrijving';
	$lang['agenda']['by']			   = 'Door';
	$lang['agenda']['time']			   = 'Tijd';
	$lang['agenda']['_add']		       = 'Het toevoegen van een afspraak is heel simpel, je vult <u>alles</u> in en je drukt op Verstuur!';
	$lang['agenda']['date']            = 'Datum';
	$lang['agenda']['change']		   = 'Verander';
	$lang['agenda']['day']			   = 'Dag';
	$lang['agenda']['month']		   = 'Maand';
	$lang['agenda']['year']			   = 'Jaar';
	$lang['agenda']['time']			   = 'Tijd';
	$lang['agenda']['send']			   = 'Verzend!';
	$lang['agenda']['reset']           = 'Herstel';
	$lang['agenda']['wk']		       = 'WK'; //week
	$lang['agenda']['added']		   = 'De afspraak is succesvol toegevoegd.';
	$lang['agenda']['notadded']		   = 'Errror! Je hebt niet alle verplichte waardes ingevuld!';
	$lang['agenda']['selected']        = 'Geselecteerd';
	$lang['agenda']['datetoday']       = 'Datum Vandaag';
	$lang['agenda']['week']			   = 'Week';
	$lang['agenda']['wholeday']        = 'Gehele Dag';
	$lang['agenda']['emptyday']		   = 'Geen Afspraken';

	#WYSIWYG Related
	#$lang['wysiwyg']['']			   = '';
	$lang['wysiwyg']['bold']		   = 'Vet';
	$lang['wysiwyg']['italic']		   = 'Schuin';
	$lang['wysiwyg']['underline']      = 'Onderstreept';
	$lang['wysiwyg']['leftalgin']	   = 'Links uitgelijnt';
	$lang['wysiwyg']['center']		   = 'Gecentreerd';
	$lang['wysiwyg']['rightalgin']	   = 'Rechts uitgelijnt';
	$lang['wysiwyg']['justifyalgin']   = 'Onafgebroken';
	$lang['wysiwyg']['orderedlist']	   = 'Geordende lijst';
	$lang['wysiwyg']['onorderedlist']  = 'Ongeorderde lijst';
	$lang['wysiwyg']['fontsize']	   = 'Tekst groote';
	$lang['wysiwyg']['fontfamily']     = 'Lettertype';
	$lang['wysiwyg']['fontformat']	   = 'Tekstformaat';
	$lang['wysiwyg']['paragraph']      = 'Paragraaf';
	$lang['wysiwyg']['pre']            = 'Normaal';
	$lang['wysiwyg']['h6']             = 'Kop 6';
	$lang['wysiwyg']['h5']             = 'Kop 5';
	$lang['wysiwyg']['h4']             = 'Kop 4';
	$lang['wysiwyg']['h3']             = 'Kop 3';
	$lang['wysiwyg']['h2']             = 'Kop 2';
	$lang['wysiwyg']['h1']             = 'Kop 1';
	$lang['wysiwyg']['identtext']      = 'Inspringen';
	$lang['wysiwyg']['removeident']    = 'Terugspringen';
	$lang['wysiwyg']['addimage']       = 'Plaatje Toevoegen';
	$lang['wysiwyg']['uploadimg']      = 'Plaatje Uploaden (werkt nog niet!)';
	$lang['wysiwyg']['link']		   = 'Link';
	$lang['wysiwyg']['unlink']         = 'Verwijder Link';
	$lang['wysiwyg']['textcolor']      = 'Tekst Kleur';
	$lang['wysiwyg']['bgcolor']        = 'Achtergrond Kleur';
	$lang['wysiwyg']['subscript']      = 'Subscript';
	$lang['wysiwyg']['superscript']    = 'Superscript';
	$lang['wysiwyg']['strike']         = 'Doorstreept';
	$lang['wysiwyg']['removeformat']   = 'Verwijder Opmaak';
	$lang['wysiwyg']['horizontalrule'] = 'Horizontale Regel';
	$lang['wysiwyg']['edithtml']       = 'Bewerk HTML';
	$lang['wysiwyg']['addeditimg']     = 'Maak/Bewerk Plaatje';
	$lang['wysiwyg']['nourl']          = 'Geen Link!';
	$lang['wysiwyg']['uploaderror']    = 'Upload Fout';
	$lang['wysiwyg']['width']          = 'Breedte';
	$lang['wysiwyg']['height']         = 'Hoogte';
	$lang['wysiwyg']['invalidid']      = 'Geen Geldige Youtube Url';
	
	#Forum related
	$lang['forum']['cat']              = 'Catagorie';
	$lang['forum']['topics']           = 'Onderwerpen';
	$lang['forum']['last']             = 'Laatste';
	$lang['forum']['topic']            = 'Onderwerp';
	$lang['forum']['reactions']        = 'Reacties';
	$lang['forum']['vote']			   = 'Stem';
	$lang['forum']['result']		   = 'Resultaat';
    $lang['forum']['noreactions']      = 'Geen Reacties';
	$lang['forum']['closed']           = 'Dit Onderwerp Is Gesloten, U Kunt Niet Reageren';
	$lang['forum']['post']			   = 'Post';
	$lang['forum']['username']         = 'Gebruikersnaam';
	$lang['forum']['message']          = 'Bericht';
	$lang['forum']['guest']			   = 'Gast';
	$lang['forum']['newtopic']		   = 'Nieuw Topic Aanmaken';
	$lang['forum']['name']		       = 'Onderwerp';
	$lang['forum']['sticky']		   = 'Sticky';
	$lang['forum']['protected']		   = 'Beveiligd';
	$lang['forum']['reset']		       = 'Herstel';
	$lang['forum']['no']		       = 'Neen';
	$lang['forum']['yes']		 	   = 'Ja';
	$lang['forum']['submit']		   = 'Opslaan';
	$lang['forum']['everyone']		   = 'Iedereen';
	$lang['forum']['loggedin']		   = 'Ingelogde Leden';
	$lang['forum']['vips']		  	   = 'VIP`S';
	$lang['forum']['moderators']	   = 'Moderators';
	$lang['forum']['admins']           = 'Administrators';
	$lang['forum']['captcha']          = 'Foute Captcha Code';
	$lang['forum']['topicerror']	   = 'Fout Kon Geen Topic Maken';
	$lang['forum']['closed']	       = 'Gesloten';
	$lang['forum']['noaccess']		   = 'Geen Rechten Om Dit Topic Te Zien!<br>U Heeft Niveau "%s" En U Heeft Niveau "%s" Nodig';
	$lang['forum']['suredel']	 	   = 'Weet U Zeker Dat U Uw Post/Topic (%s)\\nWilt Verwijderen?';

	# Register/Login/Profile (orginal=1module)
	# Userlist Related
	$lang['site']['userlist']          = 'Leden Lijst';
	$lang['userlist']['module']        = 'Leden Lijst';
	$lang['profile']['hidden']		   = 'Verborgen';
	$lang['profile']['profile']	       = 'Profiel';
	$lang['profile']['id']		       = 'Lidnummer';
	$lang['profile']['username']	   = 'Gebruikersnaam';
	$lang['profile']['realname']	   = 'Echte naam';
	$lang['profile']['email']	       = 'Email Adres';
	$lang['profile']['age']		       = 'Leeftijd';
	$lang['profile']['website']		   = 'Website';


	$lang['register']['erroruserfakemail']    = 'Email Adres Klopt <u><b>NIET</b></u>';
	$lang['register']['yes']           = 'Ja';
	$lang['register']['no']            = 'Neen';
	$lang['register']['hideprofile']   = 'Verberg Profiel';
	$lang['register']['username']      = 'Gebruikersnaam';
	$lang['register']['realname']      = 'Echte Naam';
	$lang['register']['hiderealname']  = 'Verberg Echte Naam';
	$lang['register']['email'] 		   = 'Email Adres';
	$lang['register']['hideemail']     = 'Verberg Email Adres';
	$lang['register']['password']      = 'Wachtwoord';
	$lang['register']['confirm']       = 'Wachtwoord Controle';
	$lang['register']['website']       = 'Website';
	$lang['register']['birthday']      = 'Verjaardag';
	$lang['register']['hidebirthday']  = 'Verberg Verjaardag';
	$lang['register']['text']          = 'Persoonlijke Text';
	$lang['register']['reset']         = 'Herstel';
	$lang['register']['submit']        = 'Verzenden';
	$lang['register']['passnotmatch']  = 'De 2 Wachtwoorden Komen Niet Overeen';
	$lang['register']['maked']         = 'Uw Account Is Gemaakt';
	$lang['register']['error']		   = 'Uw Account Is Niet Gemaakt';
	$lang['register']['errorusermail'] = 'Email Adres Is Al Gebruikt, Of Gebruikersnaam Is Reeds Gebruikt';
	$lang['register']['logout']        = 'Uitloggen';
	
	$lang['login']['notexists']		   = 'Gebruiker "%s" Bestaat niet';
	$lang['login']['wrongpass']		   = 'Vekeerd Wachtwoord';
	$lang['login']['loggedin']         = 'Ingelogd';
	
	#Admin Related
	$lang['admin']['moderror']		   = 'Module "%s" Kan Niet Geconfigureerd woorden!';
	$lang['admin']['config']           = 'Site Configuratie';
	$lang['admin']['modules']          = 'Module Configuratie';
	$lang['admin']['pages']			   = 'Pagina`s Configuratie';
	$lang['admin']['topmenu']		   = 'Bovenste Menu Configuratie';
	$lang['admin']['menu']		       = 'Menu Configuratie';
	$lang['admin']['editvalues']	   = 'Bewerk Hieronder Wat U Wilt Wijzigen<br>';
	$lang['admin']['warnvalues']       = 'Gebruik Dit Alleen Als Je Weet Wat Je Doet!';
	$lang['admin']['suredel']		   = 'Weet U Zeker,\\nDat U \\\'\\\'%s\\\'\\\' met waarde \\\'\\\'%s\\\'\\\' Wilt Verwijderen?';
	$lang['admin']['those']            = '%s is voor email publiceeren bij gastenboek, %s is welke modules er automatisch geladen moeten woorden "~" is een scheidingsteken voor meerderde modules';
	$lang['admin']['save']             = 'Opslaan';
	$lang['admin']['reset']            = 'Herstel';
	$lang['admin']['del']              = 'Verwijderen';	
	$lang['admin']['deleted']          = 'Configuratie Parameter %s Verwijderd.';
	$lang['admin']['updated']          = 'Configuratie Parameter %s Aangemaakt/Veranderd.';
	$lang['admin']['errdeleted']       = 'Fout: Kon Configuratie Parameter %s Niet Verwijderen';
	$lang['admin']['errupdated']       = 'Fout: Kon Configuratie Parameter %s Niet Aanmaken/Veranderen';
	$lang['admin']['newvalue']         = 'Nieuw!';
	$lang['admin']['example']          = 'vo:or=beeld';
	$lang['admin']['suredelpage']      = 'Weet U Zeker,\\\nDat U Pagina \\\'\\\'%s\\\'\\\' Wilt Verwijderen?';
	$lang['admin']['newpage']          = 'Nieuwe Pagina';
	$lang['admin']['editedpage']	   = 'Bewerkt!';
	$lang['admin']['noteditedpage']	   = 'Niet Bewerkt!';
	$lang['admin']['edit']             = 'Bewerk';
	$lang['admin']['content']          = 'Inhoud';
	$lang['admin']['title']            = 'Titel';
	$lang['admin']['createdpage']	   = 'Pagina Gemaakt';
	$lang['admin']['notcreatedpage']   = 'Pagina Niet Gemaakt';
	$lang['admin']['deletedpage']      = 'Pagina Verwijderd';
	$lang['admin']['notdeletedpage']   = 'Pagina Niet Verwijderd';
?>