<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################

	function sharebuttons ( $show = array ("facebook","twitter","windowslivemessenger","hyves","linkedin") )
		{
			global $conf;
			
			$nums = 5;
			
			if ( preg_match ( "#\.#" , $_SERVER['REQUEST_URI'] ) )
				{
					$thisurl = $conf['site']['url'] . 'page/' . $_GET['pag'];
				}
			else
				{
					$thisurl = $conf['site']['url'] . substr ( $_SERVER['REQUEST_URI'] , 1 , strlen ( $_SERVER['REQUEST_URI'] ) );
				}
				
			$width = floor ( 100 / $nums ) ;
?>
<!-- Share Buttons :) -->
<table style="border: none;" width='100%'>
	<tr>
		<!-- Twitter -->
			<td class='twitter' id='twitter' name='twitter' width='<?php echo $width-10; ?>%'>
				<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="WDGPROJECTS">Tweet</a>
				<script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
			</td>

		<!-- Windows Live Messenger -->
			<td class='windowslivemessenger' id='windowslivemessenger' name='windowslivemessenger' width='<?php echo $width; ?>%'>
				<a href="http://profile.live.com/badge?url=<?php echo $thisurl; ?>&amp;wa=wsignin1.0" target="_new">
					<img src="<?php echo $conf['site']['url']; ?>template/admin/images/share.png" width="75px" height="25px" border="0">
				</a>
			</td>

		<!-- Hyves -->
			<td class='hyves' id='hyves' name='hyves' width='150px'>
				<iframe src="http://www.hyves.nl/respect/button?url=<?php echo $thisurl; ?>&icon=1" style="border: medium none; overflow:hidden; width:150px; height:21px;" scrolling="no" frameborder="0" allowTransparency="true" >
					Please Upgrade Your Browser!
				</iframe>
			</td>

		<!-- Linked In -->
			<td class='linkedin' id='linkedin' name='linkedin' width='<?php echo $width; ?>%'>
				<script type="text/javascript" src="http://platform.linkedin.com/in.js"></script>
				<script type="in/share" data-url="<?php echo $thisurl; ?>" data-counter="top"></script>
			</td>
		
		<!-- Facebook -->
			<td class='facebook' id='facebook' name='facebook' width='<?php echo $width; ?>%'>
				<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
				<fb:like href="<?php echo $thisurl; ?>" layout="box_count" show_faces="true" width="450"></fb:like>
			</td>
	</tr>
</table>
<!-- /Share Buttons :) -->
<?php
	}
	
	ob_start();
	$shareme = sharebuttons ( ) ;
	$shareme = ob_get_contents();
	ob_end_clean();
	
	$wdgssautoload[] = array ( "share" , $shareme ) ;

?>