<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















function _adminforum()
	{ 

	global $conf,$lang;

	if ( isset ( $_POST['addcat'] ) )
		{
			$q = $conf['database']['db'] -> query ( "INSERT INTO `{$conf['database']['pref']}forum` (`id` ,`catname` ,`protected`)\nVALUES (NULL , '{$_POST['addcat']}', '2');" );
		}
	if ( isset ( $_POST['delcat'] ) )
		{
			$q = $conf['database']['db'] -> query ( "DELETE FROM `{$conf['database']['pref']}forum` WHERE `id`='{$_POST['delcat']}'" ); //echo dump($q);
		}

	?>
	<a href='<?php echo $_SERVER['REQUEST_URI']; ?>'>Catagory Managment</a><br><br>
	Add:<br>
	<form method="POST" action="<?php echo $_SERVER['REQUEST_URI']; ?>">
	 <input type="text" name="addcat">
	 <input type="submit" value="<?php echo $lang['admin']['save']; ?>">
	</form>
	<hr />
	DEL:<br>
	<?php
	$q = $conf['database']['db'] -> query ( "SELECT * FROM `{$conf['database']['pref']}forum` ORDER BY `id`" );
	$q = $conf['database']['db'] -> fetch ( $q, 'array' );
for ( $i=0; $i<sizeof($q); $i++ )
{
?>
	<form method="POST" action="<?php echo $_SERVER['REQUEST_URI']; ?>">
	 <input type="text" value="<?php echo $q[$i]['catname']; ?>" readonly="readonly">
	 <input type="hidden" name="delcat" value="<?php echo $q[$i]['id']; ?>">
	 <input type="submit" value="<?php echo $lang['admin']['del']; ?>">
	</form><br>
<?php
}
	}
?>