<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################
















 if ( isset ( $_GET['what'] ) && isset ( $_GET['id'] ) )
	{ 
		$what	=	$_GET['what']; 
		$id		=	$_GET['id'];
		$G 		=   ( ( $what == 'topic' ) ? 'text' : 'reaction' ) ;
		
		$s = "SELECT * FROM `{$conf['database']['pref']}forum_{$what}s` WHERE `id`='{$id}' LIMIT 0,1;";
		$se = $conf['database']['db'] -> query($s);
		$se = $conf['database']['db'] -> fetch ( $se, 'array' );
		$se = $se[0];

		if ( 
			($se['by'] == @$_SESSION['login']) Or
			(@$_SESSION['status'] >= 3)
		   )
		{
		
		$a=array();
			if ( $what == 'topic' )
				{
							$s1 = "DELETE FROM `{$conf['database']['pref']}forum_topics` WHERE `id`='{$id}';";								
							$s2 = "DELETE FROM `{$conf['database']['pref']}forum_reactions` WHERE `topicid`='{$id}';";
							$a[] = $conf['database']['db'] -> query($s1);
							$a[] = $conf['database']['db'] -> query($s2);
							$X = 'cat/' . $se['catid'];
				}
			else
				{
							$s1 = "DELETE FROM `{$conf['database']['pref']}forum_{$what}s` WHERE `id`='{$id}';";
							$a[] =$conf['database']['db'] -> query($s1);
							$X = $se['catid'] . '/' . $se['topicid'];
				}
			ga($conf['site']['url'] . 'forum/' . $X);
		}
	}
?>