<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















?>
<table>
	<tr>
		<td>
			id
		</td>
		<td>
			Username
		</td>
		<td>
			Realname
		</td>
		<!--
		<td>
			Age
		</td>
		<td>
			Sex
		</td>
		-->
	</tr>
<?php
 $sql = "SELECT `id`,`username`,`realname`,`hiderealname`,`birthday`,`hidebirthday`,`status` FROM `{$conf['database']['pref']}users` ORDER BY `status`"; 
 $sql = $conf['database']['db']->query($sql);
 $sql = $conf['database']['db']->fetch($sql,'array');
 
 for ( $i=0; $i<sizeof($sql); $i++ )
 {
  $x = (!is_even($i)?'userlist_even':'userlist_not_even');
  echo "
  <tr>
  <td class='{$x}'>{$sql[$i]['id']}</td>
  <td class='{$x}'><a href='{$conf['site']['url']}profile/{$sql[$i]['username']}'>{$sql[$i]['username']}</a></td>
  <td class='{$x}'>" . ((!$sql[$i]['hiderealname'])?$sql[$i]['realname']:'HIDDEN') . "</td>
<!--
  <td class='{$x}'>{$sql[$i]['id']}</td>
  <td class='{$x}'>{$sql[$i]['id']}</td>
-->
  </tr>
  ";
 }
?>
</table>