<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















 # {REP}

function get_news($par=0)
{
 global $lang,$conf;
 $a = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}news` ORDER BY `datetime` DESC");
 $a = $conf['database']['db'] -> fetch ( $a, 'array' );
 $r = null;
 if ( is_array ( $a ) ) 
 {
	 for ( $i=0; $i<sizeof($a); $i++ ) 
		 {
			$a[$i]['datetime'] = nldate($a[$i]['datetime']);
			$r .= "<div class='news_post'>\n <div class='news_title'>\n  {$a[$i]['name']}\n </div>\n <div class='news_content'>\n  <span style='algin: right; float: right;'>\n   <small>{$a[$i]['datetime']}</small>\n  </span>\n  {$a[$i]['text']}<br>\n  <span style='algin: right; float: right;'>\n   <small>{$lang['news']['by']} <a href='/profile/{$a[$i]['by']}'>{$a[$i]['by']}</a></small>\n  </span>\n </div>\n</div><br /><br />";
		 }
	 return $r;
 }
 else
 {
	return "No News?";
 }
}
?>