<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















if ( !defined ( 'in_wdgss' ) )
	 {
	  exit("You`ll Missed This Action");
	 }

$adminmodules = array("home","config");
$modconf = array();

for($i=0; $i<sizeof(@$conf['module']['list']); $i++)
	{ 
		if ( file_exists ( $s = "modules/" . $conf['module']['list'][$i] . "/admin.php" ) )
			{
				include $s;
				$modconf[] = $conf['module']['list'][$i];
			}
	}
function admin_login()
	{
		global $conf,$lang;
		
		if ( isset ( $_POST['login'] ) && isset ( $_POST['password'] ) )
			{
			if ( $_POST['login'] == "Wes" && $_POST['password'] == "DEFDONTWORK;)" )
				{
					$_SESSION['login_admin'] = "Wes";
					ga ( $conf['site']['url'] . "admin.pag" );
				}
			else
				{
					echo "Wrong Password";
				}
			}
		else
			{
				echo "<form method='post' action='" . $conf['site']['url'] . "admin.pag" . "'><table><tr><td>{$lang['site']['username']}</td><td><input type='text' name='login'></td></tr><tr><td>{$lang['site']['password']}</td><td><input type='password' name='password'></td></tr><tr><td></td><td><input type='submit' value='{$lang['site']['login']}'></td></tr></table>";
			}
	}

function _adminconfig()
	{
		global $conf,$lang;
		$r = null;
		
		if ( isset ( $_POST['del'] ) )
			{
				$_POST['del'] = secure($_POST['del']);
				if ( $conf['database']['db'] -> query ($q = "DELETE FROM `{$conf['database']['pref']}config` WHERE `config` = '{$_POST['del']}' LIMIT 1") )
					{
						$r .= sprintf($lang['admin']['deleted'],$_POST['del']) . "<br>";
					}
				else
					{
						$r .= sprintf($lang['admin']['errdeleted'],$_POST['del']) . "<br>";
					}
			}
		
		if ( isset ( $_POST['make'] ) ) 
			{
				if ( is_array ( $_POST['make'] ) ) 
					{
						$conp = $_POST['make'][0];
						$_POST['make'] = secure($_POST['make'][0] . '=' . $_POST['make'][1]);
					}
				else
					{
						$_POST['make'] = secure($_POST['make']);
						$conp          = secure($_POST['make']);
					}
				
				if ( preg_match ( "#site\:theme#", $_POST['make'] ) ) #LAYOUT FIX
					{
						$conf['database']['db'] -> query ( $q = "DELETE FROM `{$conf['database']['pref']}config` WHERE `config` LIKE '%site:theme%';" ) ;
						$conf['database']['db'] -> query ( $q = "DELETE FROM `{$conf['database']['pref']}config` WHERE `config` LIKE '%site\:theme%';" ) ;
					}
				
				if ( $conf['database']['db'] -> query ( $q = "INSERT INTO `{$conf['database']['pref']}config` ( `config` ) \n VALUES ( '{$_POST['make']}' );") )
					{
						$r .= sprintf($lang['admin']['updated'],$conp) . "<br>";
					}
				else
					{
						$r .= sprintf($lang['admin']['errupdated'],$conp) . "<br>";
					}
					$r .= renew(0,$conf['site']['url'] . "admin/config");
			}
			else
			{
				
				$q = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}config`");
				$a = $conf['database']['db'] -> fetch ( $q, 'array' );
				$r.= $lang['admin']['editvalues'];
				$r.= $lang['admin']['warnvalues'];
				$r.= "<br><small>" . sprintf($lang['admin']['those'],'guestbook:email','module:autoloadthose') . "</small>"; 
				$r.= "<br><table>";
				
				$themes = array();
				$o = opendir('template');
				while ( ( $f = readdir ( $o ) ) !== false ) 
				{
				 if ( $f != '.' && $f != '..' && is_dir("template/" . $f) && $f != 'admin' && $f != 'smilies' )
				  $themes[] = '<option name=\'' . $f .'\'' . (($conf['site']['theme']==$f)?' Selected':null) . '>' . $f . '</option>';
				}
				sort($themes);
				$themes = implode('',$themes);
						
				$langs = null;
				$o = opendir('lang');
				$got = array();
				while ( ( $f = readdir ( $o ) ) !== false ) 
				{
				 if ( $f != '.' && $f != '..' && !in_array($f,$got) ) 
				 {
					$got[]  = $f;
					$fe     = explode(".", $f);
					$f      = $fe[0];
					$langs .= '<option name=\'' . $f .'\'' . (($conf['site']['lang']==$f)?' Selected':null) . '>' . $f . '</option>';
				 }
				}
				
				$mods = array();
				$o = opendir('modules');
				while ( ( $f = readdir ( $o ) ) !== false ) 
				{
				 if ( $f != '.' && $f != '..' )
				  $mods[] = $f;
				}
				
				for ( $i=0; $i<sizeof($a); $i++ )
				{
						preg_match_all("#(.*)\:(.*)=(.*)#",$a[$i]['config'],$out);
					if (!preg_match("#site\:url#",$a[$i]['config']) && !preg_match("#site\:link#",$a[$i]['config']) && !preg_match("#site\:(theme|lang)#",$a[$i]['config']) && !in_array($out[1][0],$mods))
					{
					$ex = explode("=",$a[$i]['config']);
					if ( !isset ( $ex[1] ) ) $ex[1]=null;
					$r .= "<tr><td>{$ex[0]}</td><td><form method='post' action='{$conf['site']['url']}admin/config'><input type='hidden' name='del' value='{$a[$i]['config']}'><input type='hidden' name='make[]' value='{$ex[0]}'><input type='text' name='make[]' value='{$ex[1]}'></td><td><input type='submit' value='{$lang['admin']['save']}'></form></td><td><form method='post' action='{$conf['site']['url']}admin/config'><input type='hidden' name='del' value='{$a[$i]['config']}'><input type='submit' value='{$lang['admin']['del']}' onclick=\"return confirm('" . sprintf($lang['admin']['suredel'],$ex[0],$ex[1]) . "');\"></form></td><td></td></tr>";
					}
					elseif ( preg_match("#(theme|site)\:(override|theme|lang)#",$a[$i]['config']) )
					{
									$ex = explode("=",$a[$i]['config']);
									if ( !isset ( $ex[1] ) ) $ex[1]=null;
					
						if ( preg_match("#site\:theme#",$a[$i]['config']) )
						 {
							$r .= "<tr><td>{$ex[0]}</td><td><form method='post' action='{$conf['site']['url']}admin/config'><input type='hidden' name='del' value='{$a[$i]['config']}'><input type='hidden' name='make[]' value='{$ex[0]}'><select name='make[]'>{$themes}</select></td><td><input type='submit' value='{$lang['admin']['save']}'></form></td><td><form method='post' action='{$conf['site']['url']}admin/config'><input type='hidden' name='del' value='{$a[$i]['config']}'><!--input type='submit' value='{$lang['admin']['del']}' onclick=\"return confirm('" . sprintf($lang['admin']['suredel'],$ex[0],$ex[1]) . "');\"--></form></td><td></td></tr>";
						 }
						else
						 {
							$r .= "<tr><td>{$ex[0]}</td><td><form method='post' action='{$conf['site']['url']}admin/config'><input type='hidden' name='del' value='{$a[$i]['config']}'><input type='hidden' name='make[]' value='{$ex[0]}'><select name='make[]'>{$langs}</select></td><td><input type='submit' value='{$lang['admin']['save']}'></form></td><td><form method='post' action='{$conf['site']['url']}admin/config'><input type='hidden' name='del' value='{$a[$i]['config']}'><!--input type='submit' value='{$lang['admin']['del']}' onclick=\"return confirm('" . sprintf($lang['admin']['suredel'],$ex[0],$ex[1]) . "');\"--></form></td><td></td></tr>";
						 }
					}
					else { /* nothing */ }
				}
				$r .= "<tr><td>" . $lang['admin']['newvalue'] . "</td><td><form method='post' action='{$conf['site']['url']}admin/config'><input type='text' name='make' value='" . $lang['admin']['example'] . "'></td><td><input type='submit' value='{$lang['admin']['save']}'></form></td><td>&nbsp;</td></tr>";
				$r .= "</table>";
		}
		return $r;
	}

function _adminmodules()
	{
		global $conf,$lang,$modconf;
		$r = "<a href='{$conf['site']['url']}admin/modules'>{$lang['admin']['modules']}</a><br><br>";
		if ( isset ( $_GET['mod'] ) )
			{
				if ( function_exists ( "_admin" . $_GET['mod'] ) )
					{
						@ob_start();
							eval("global \$conf,\$lang; \$a = _admin" . $_GET['mod'] . "(); if ( !empty ( \$a ) ) echo \$a;");
							$r .= ob_get_contents();
						@ob_end_clean();
					}
				else
					{
						$r .= sprintf($lang['admin']['moderror'],$_GET['mod']);
					}
			} 
		else
			{
				$r .= "<ul>";
				for ( $i=0; $i<sizeof($modconf); $i++ )
				{
					$lang[$modconf[$i]]['module'] = (isset($lang[$modconf[$i]]['module'])?$lang[$modconf[$i]]['module']:$modconf[$i]);
					$r .= "<li><a href='{$conf['site']['url']}admin/module/{$modconf[$i]}'>{$lang[$modconf[$i]]['module']}</a></li>";
				}
				$r .= "</ul>";
			}
			return $r;
	}
function _adminhome() 
	{
		global $lang,$conf;
		$cats = array("config","modules","pages");
		return "
<table>
<tr><td>
		<a href='{$conf['site']['url']}admin/config' title='{$lang['admin']['config']}'><img width='64' height='64' src='{$conf['site']['url']}template/admin/images/config.png' alt='{$lang['admin']['config']}'><br>{$lang['admin']['config']}</a>&nbsp;&nbsp;&nbsp;&nbsp;
</td><td>
		<a href='{$conf['site']['url']}admin/topmenu' title='{$lang['admin']['topmenu']}'><img width='64' height='64' src='{$conf['site']['url']}template/admin/images/topmenu.png' alt='{$lang['admin']['topmenu']}'><br>{$lang['admin']['topmenu']}</a>&nbsp;&nbsp;&nbsp;&nbsp;
</td><td>
		<a href='{$conf['site']['url']}admin/menu' title='{$lang['admin']['menu']}'><img width='64' height='64' src='{$conf['site']['url']}template/admin/images/menu.png' alt='{$lang['admin']['menu']}'><br>{$lang['admin']['menu']}</a>&nbsp;&nbsp;&nbsp;&nbsp;
</td>
<!--</tr><tr>-->
<td>
		<a href='{$conf['site']['url']}admin/modules' title='{$lang['admin']['modules']}'><img width='64' height='64' src='{$conf['site']['url']}template/admin/images/modules.png' alt='{$lang['admin']['modules']}'><br>{$lang['admin']['modules']}</a>&nbsp;&nbsp;&nbsp;&nbsp;
</td><td>
		<a href='{$conf['site']['url']}admin/pages' title='{$lang['admin']['pages']}'><img width='64' height='64' src='{$conf['site']['url']}template/admin/images/pages.png' alt='{$lang['admin']['pages']}'><br>{$lang['admin']['pages']}</a>
</td><td>
		<a href='{$conf['site']['url']}admin/update' title='{$lang['admin']['pages']}'><img width='64' height='64' src='{$conf['site']['url']}template/admin/images/update.png' alt='Update'><br>Update</a>
</td>
</tr></table>		";
	}

function _adminpages()
	{
		global $conf,$lang;
		$u = $conf['site']['url'] . "admin/pages&";
		$r = '<a href=\'' . $u . '\'>&lt;--</a><br><br>';

			if ( isset ( $_POST['content'] ) )
				{
					# => #
					$_POST['content'] = strip($_POST['content']);
				}
		#// wysiwyg = wysiwyg('textarea') //
		if ( isset ( $_GET['editpage'] ) )
			{
				if ( isset ( $_POST['opage'] ) && isset ( $_POST['page'] ) && isset ( $_POST['content'] ) )
					{
						$_POST['content'] = preg_replace("#\\\"#","\"",$_POST['content']);
						$w = $conf['database']['db'] -> query ( "UPDATE `{$conf['database']['pref']}pages` SET `page`='" . secure($_POST['page']) . "', `content`='" . ($_POST['content']) . "' WHERE `page`='" . secure($_POST['opage']) . "'");
						if ($w)
						{
							$r .= $lang['admin']['editedpage'];
						}
						else
						{
							$r .= $lang['admin']['noteditedpage'];
						}
					} 
				else
					{
						$w = $conf['database']['db'] -> query ( "SELECT `content`,`page` FROM `{$conf['database']['pref']}pages` WHERE `page`='{$_GET['editpage']}'" );
						$w = $conf['database']['db'] -> fetch ( $w, 'array' );
						$w = $w[0];
						$r .= "<form method='post' action='{$u}editpage={$_GET['editpage']}'><table><tr><td>{$lang['admin']['title']}</td><td><input type='hidden' name='opage' value='{$w['page']}'><input type='text' name='page' value='{$w['page']}'></td></tr><tr><td>{$lang['admin']['content']}</td><td><textarea id='content' name='content' rows='25' cols='50'>{$w['content']}</textarea></td></tr><tr><td></td><td><input type='submit' value='{$lang['admin']['save']}'></td></tr></form></table>" . wysiwyg('content');
					}
			}
		elseif ( isset ( $_GET['newpage'] ) )
			{
				if ( isset ( $_POST['page'] ) && isset ( $_POST['content'] ) )
					{
						$_POST['content'] = preg_replace("#\\\"#","\"",$_POST['content']);
						$w = $conf['database']['db'] -> query ( "INSERT INTO `{$conf['database']['pref']}pages` ( `page`,`content` ) \n VALUES ( '{$_POST['page']}','{$_POST['content']}' );");
						if ($w)
							{
								$r .= $lang['admin']['createdpage'];
							}
						else
							{
								$r .= $lang['admin']['notcreatedpage'];
							}
					} 
				else
					{
						$r .= "<form method='post' action='{$u}newpage=true'><table><tr><td>{$lang['admin']['title']}</td><td><input type='text' name='page'></td></tr><tr><td>{$lang['admin']['content']}</td><td><textarea id='content' name='content' rows='25' cols='50'></textarea></td></tr><tr><td></td><td><input type='submit' value='{$lang['admin']['save']}'></td></tr></form></table>" . wysiwyg('content');
					}
			}
		elseif ( isset ( $_GET['deletepage'] ) )
			{
				$_GET['deletepage'] = secure($_GET['deletepage']);
				$w = $conf['database']['db'] -> query ( "DELETE FROM `{$conf['database']['pref']}pages` WHERE `page`='{$_GET['deletepage']}';");
				if ($w)
					{
						$r .= $lang['admin']['deletedpage'];
					}
				else
					{
						$r .= $lang['admin']['notdeletedpage'];
					}
			}
		else
			{
				$w = $conf['database']['db'] -> query ( "SELECT `page` FROM `{$conf['database']['pref']}pages`" );
				$w = $conf['database']['db'] -> fetch ( $w, 'array' );
				$r .= '<table>';
				for($i=0; $i<sizeof($w); $i++)
					{
						$r .= "<tr><td><a href='{$conf['site']['url']}page/{$w[$i]['page']}' target='_new'>{$w[$i]['page']}</a></td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td><a href='{$u}editpage={$w[$i]['page']}'>{$lang['admin']['edit']}</a></td><td>&nbsp;&nbsp;</td><td><a href='{$u}deletepage={$w[$i]['page']}' onclick=\"return confirm('" . sprintf($lang['admin']['suredelpage'],$w[$i]['page']) . "');\">{$lang['admin']['del']}</a></td></tr>";
					}
				$r .= '</table>';
				$r .= "<br><a href='{$u}newpage=true'>{$lang['admin']['newpage']}</a>";
			}
		return $r;
	}

function _admingetmenus($ac) 
	{
		global $conf,$lang;
		$menu = array();
			$ac = explode(".",$ac);
			$ac = $ac[0];
		#Get From Sql
		$w = $conf['database']['db'] -> query ( "SELECT `page` FROM `{$conf['database']['pref']}pages`" );
		$w = $conf['database']['db'] -> fetch ( $w, 'array' );
		for ($i=0; $i<sizeof($w); $i++) 
			{
			    $file=array();
			    $file[0]=$w[$i]['page'];
				$menu[] = $file[0];
			}
		unset($file);
		
		#Get From ./pages
		$d = opendir($dir = 'pages');
		while ( ( $file = readdir($d) ) !== false )
			 {
				  if ( $file != '.' && $file != '..' && !is_dir($dir . '/' . $file) )
					  {
						$file = explode(".",$file);
						$menu[] = $file[0];
					  }
			}
		unset($file);
				
		#Get From ./modules/{module}/page.php
		$d = opendir($dir = 'modules');
		while ( ( $file = readdir($d) ) !== false )
			 {
				  if ( $file != '.' && $file != '..' && is_dir($dir . '/' . $file) && file_exists($dir . '/' . $file . '/page.php' ) )
					  {
						$file = explode(".",$file);
						$menu[] = $file[0];
					  }
			}
		unset($file);
			
			$a = null;
			for ( $i=0; $i<sizeof($menu); $i++ )
			{
			 $a .= '<option name=\'' . $menu[$i] . '\' value=\'' . $menu[$i] . '\'' . (($ac==$menu[$i])?' selected':null). '>' . ((isset($lang['site'][$menu[$i]])?$lang['site'][$menu[$i]]:$menu[$i])) . '</option>'; 
			}
			$menu = $a;
			
			return $menu;
			
	}

function _admintopmenu()
	{
		global $conf,$lang; $r=null;
		if ( $_SERVER['REQUEST_METHOD'] == "POST" ) 
			{
				//for ( $i = 0; $i < (sizeof($_POST)/2); $i++ )
					//{
							for ( $i=1; $i<11; $i++ )
								{
									$a1 = false;
									$a2 = false;
									$conf['database']['db'] -> query("DELETE FROM `{$conf['database']['pref']}config` WHERE `config` LIKE '%site:url{$i}%'");
								    $conf['database']['db'] -> query("DELETE FROM `{$conf['database']['pref']}config` WHERE `config` LIKE '%site:link{$i}%'");
								    
								    $w = 'link';
								    $e = @$_POST[$w.'_'.$i];
								    
								    if ( isset ( $_POST[ $w . '_' . $i ] ) && !empty( $e ) )
								    {
										$conf['database']['db'] -> query("INSERT INTO `{$conf['database']['pref']}config` (`config`)\nVALUES ('site:{$w}{$i}={$_POST[ $w . '_' . $i ]}');");
										$a1 = true;
									}

								    $w = 'url';
								    $e = @$_POST[$w.'_'.$i];
								    if ( isset ( $_POST[ $w . '_' . $i ] ) && !empty( $e ) )
								    {
										$conf['database']['db'] -> query("INSERT INTO `{$conf['database']['pref']}config` (`config`)\nVALUES ('site:{$w}{$i}={$_POST[ $w . '_' . $i ]}.pag');");
										$a2 = true;
								    }
								    
								    if ( $a1 && $a2 )
								     $e = 'V';
								    Else
								     $e = 'X';
								     
								    $r .= "{$i}/10 => {$e}<br />";
								}
					//}
					//echo dump($conf['database']['db']->debug);
					$r .= renew(1,"admin/topmenu");
			}
		else 
			{	
				$q = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}config`");
				$a = $conf['database']['db'] -> fetch ( $q, 'array' );
				$topmenu = array();
				for ( $i=0; $i<sizeof($a); $i++ )
					{
						if (preg_match("#site\:url#",$a[$i]['config'])) // preg_match("#site\:link#",$a[$i]['config']))
							{
								$aa = explode("=",$a[$i]['config']);
								preg_match_all("#site\:url(10|9|8|7|6|5|4|3|2|1)#",$aa[0],$uit);
								$topmenu['url' . $uit[1][0]] = $aa[1]; 
							}
						if (preg_match("#site\:link#",$a[$i]['config']))
							{
								$aa = explode("=",$a[$i]['config']);
								preg_match_all("#site\:link(10|9|8|7|6|5|4|3|2|1)#",$aa[0],$uit);
								$topmenu['link' . $uit[1][0]] = $aa[1]; 
							}
					}			

				$r .= "<form method='post'><table>";
				$tel=1;
				for ( $i=1; $i<11; $i++ )
				{
					if ( isset($topmenu['link' . $tel] ) && isset($topmenu['url' . $tel]) )
					{
						$r .= "<tr><td><input type='text' name='link_{$tel}' value='" . (isset($topmenu['link' . $tel])?$topmenu['link' . $tel]:null) . "'></td><td><select name='url_{$tel}'>" . _admingetmenus((isset($topmenu['url' . $tel])?$topmenu['url' . $tel]:false)) . "</select></td></tr>";
						$tel++;
						$i++;
					}
				}
				while ( $tel < 11 )
				{
						$r .= "<tr><td><input type='text' name='link_{$tel}' value='" . (isset($topmenu['link' . $tel])?$topmenu['link' . $tel]:null) . "'></td><td><select name='url_{$tel}'>" . _admingetmenus((isset($topmenu['url' . $tel])?$topmenu['url' . $tel]:false)) . "</select></td></tr>";				
						$tel++;
				}
				$r .= "<tr><td><input type='reset' value='{$lang['admin']['reset']}'></td><td><input type='submit' value='{$lang['admin']['save']}'></td></tr></table>";
			}
		return $r;
	}

function _adminmenu()
	{
		global $conf,$lang; $r=null;
		if ( $_SERVER['REQUEST_METHOD'] == "POST" ) 
			{
				for ( $i=1; $i<$_POST['max']; $i++ )
					{
						$a1 = false;
						$a2 = false;
						$conf['database']['db'] -> query("DELETE FROM `{$conf['database']['pref']}menu` WHERE `menu` LIKE '%menu:url{$i}%'");
					    $conf['database']['db'] -> query("DELETE FROM `{$conf['database']['pref']}menu` WHERE `menu` LIKE '%menu:link{$i}%'");
								    
					    $w = 'link';
					    $e = @$_POST[$w.'_'.$i];
								    
					    if ( isset ( $_POST[ $w . '_' . $i ] ) && !empty( $e ) )
							{
								$conf['database']['db'] -> query("INSERT INTO `{$conf['database']['pref']}menu` (`menu`)\nVALUES ('menu:{$w}{$i}={$_POST[ $w . '_' . $i ]}');");
								$a1 = true;
							}

					    $w = 'url';
					    $e = @$_POST[$w.'_'.$i];

					    if ( isset ( $_POST[ $w . '_' . $i ] ) && !empty( $e ) )
						    {
								$conf['database']['db'] -> query("INSERT INTO `{$conf['database']['pref']}menu` (`menu`)\nVALUES ('menu:{$w}{$i}={$_POST[ $w . '_' . $i ]}.pag');");
								$a2 = true;
						    }
								    
					    if ( $a1 && $a2 )
						     $e = 'V';
					    Else
						     $e = 'X';
							     
						$r .= "{$i}/{$_POST['max']} => {$e}<br />";
					}
					$r .= renew(0,$conf['site']['url']  . "admin/menu");
			}
		else 
			{	
				$q = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}menu`");
				$a = $conf['database']['db'] -> fetch ( $q, 'array' );
				$menu = array();
				$b = floor(sizeof($a)/2);
				for ( $i=floor(sizeof($a)/2)-1; $i>0; $i--) { $b .= "|{$i}"; }
				for ( $i=0; $i<sizeof($a); $i++ )
					{
						$w = isset($a[$i]['menu'])?$a[$i]['menu']:null;
						if (preg_match("#menu\:url#",$w)) // preg_match("#site\:link#",$a[$i]['config']))
							{
								$aa = explode("=",$w);
								preg_match_all("#menu\:url({$b})#",$aa[0],$uit);
								$u = @$uit[1][0];
								$menu['url' . $u] = $aa[1];
							}
						if (preg_match("#menu\:link#",$w))
							{
								$aa = explode("=",$w);
								preg_match_all("#menu\:link({$b})#",$aa[0],$uit);
								$u = @$uit[1][0];
								$menu['link' . $u] = $aa[1]; 
							}
					}			
				$r .= "<form method='post'><table><input type='hidden' name='max' value='" . floor( ( sizeof ( $a ) / 2 ) + 5 ) . "'>";
				for ( $i=1; $i<(floor((sizeof($a)/2)+5)); $i++ )
				{
					$r .= "<tr><td><input type='text' name='link_{$i}' value='" . (isset($menu['link' . $i])?$menu['link' . $i]:null) . "'></td><td><select name='url_{$i}'>" . _admingetmenus((isset($menu['url' . $i])?$menu['url' . $i]:false)) . "</select></td></tr>";
				}
				$r .= "<tr><td><input type='reset' value='{$lang['admin']['reset']}'></td><td><input type='submit' value='{$lang['admin']['save']}'></td></tr></table>";
			}
		return $r;
	}

function admin ( $action ) 
	{
		global $conf,$lang;
		$pag = "<a href='{$conf['site']['url']}admin.pag'>Admin-Home</a><br><br><br>";
		switch ( $action ) 
			{
				case 'config':
					$pag .= _adminconfig();
				break;
					
				case 'modules':
					$pag .= _adminmodules();
				break;
				
				case 'pages':
					$pag .= _adminpages();
				break;
				
				case 'menu':
					$pag .= _adminmenu();
				break;

				case 'topmenu':
					$pag .= _admintopmenu();
				break;
				
				case 'update':
				  $pag .= _UPD();
					
				default:
					$pag .= _adminhome();
				break;
			}
		return $pag;
	}	
?>