<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################

















if ( !defined ( 'in_wdgss' ) )
 {
  exit("You`ll Missed This Action");
 }

@session_start();

function generateCode($characters,$possible) 
{
	$code    = '';
	$codestr = null;
	$i = 0;
	while ($i < $characters) 
		{
			$oooooo   = substr($possible, mt_rand(0, strlen($possible)-1), 1);
			$code[]   = $oooooo;
			$codestr .= $oooooo;
			$i++;
		}
	return array($code,$codestr);
}
   
function draw_captcha($conf)
	{
		$aant       = $conf['captcha']['length'];//;"5";//this varable can be 2-40
		$height     = $conf['captcha']['height'];//;"30";
		$SQUARE     = $conf['captcha']['square'];//;"1";//this varable can be 1 = ON, 0 = OFF
		$possible   = $conf['captcha']['chars'];//;'BCDFGHJKLMNPQRSTUVWXY23456789';//Characters used in code
		$Background = strtoupper($conf['captcha']['bgcolor']);//;"Auto"; // this varible can be AUTO, WHITE, RED, GREEN, BLUE, TRANS
		$LINES      = $conf['captcha']['lines'];//"1";//Draw lines?  this varable can be 1 = ON, 0 = OFF
		$LINES_OVER = $conf['captcha']['over'];//"1";//Draw lines Over text? this varable can be 1 = ON, 0 = OFF

		if ( $Background == "TRANS" ) 
		 $conf['captcha']['square'] = 0;

		// Maak 't plaatje
		$width= $aant * 25;
		$im = imagecreate($width, $height);

		//Achtergrond kleur
		$Background = strtoupper($Background);
		
		if ($Background=="AUTO")
			{
				$bg = imagecolorallocate($im, rand(190,255), rand(190,255), rand(190,255));
			}
		elseif($Background=="WHITE")
			{
				$bg = imagecolorallocate($im, 255, 255, 255);
			}
		elseif($Background=="RED")
			{
				$bg = imagecolorallocate($im, 255 , 0, 0);
			}
		elseif($Background=="GREEN")
			{
				$bg = imagecolorallocate($im, 0, 255, 0);
			}
		elseif($Background=="BLUE")
			{
				$bg = imagecolorallocate($im, 0, 0, 255);
			}
		elseif($Background=="TRANS") 
			{
				$co = imagecolorallocate($im, 0, 0, 0);
				$bg = imagecolortransparent($im, $co);
			}
		else
			{
				$bg = imagecolorallocate($im, 255, 255, 255);
			}

		// Genereer de code
		$a       = generateCode($aant,$possible);
		$code    = $a[0];
		$codestr = $a[1];

		if( $LINES == "1" )
			{
			$i = 0;
			while( $i<($width*$height)/500) 
				{
					$noise_color = imagecolorallocate($im, rand(150,255), rand(150,255), rand(150,255));
					imageline($im, rand(0,$width), rand(0,$height), rand(0,$width), rand(0,$height), $noise_color);
					$i++;
				}
			}

		if($SQUARE=="1")
			{
				// Teken een vierkand van 2 punten
				$vierkand = imagecolorallocate($im, rand(0,255), rand(0,255), rand(0,255));
				imageline($im, 0, 0, $width, 0, $vierkand);
				imageline($im, 0, 1, $width, 1, $vierkand);
				imageline($im, $width-1, 0, $width-1, $height, $vierkand);
				imageline($im, $width-2, 0, $width-2, $height, $vierkand);
				imageline($im, $width-1, $height-1, 0, $height-1, $vierkand);
				imageline($im, $width-1, $height-2, 0, $height-2, $vierkand);
				imageline($im, 0, $height, 0, 0, $vierkand);
				imageline($im, 1, $height, 1, 0, $vierkand);
			}

		$widthpercar = 25;
		$i           = 0;
		while ($i < $aant)
			{
				$min       = ($widthpercar*$i) - 1;
				$max       = $widthpercar*$i;
				$textcolor = imagecolorallocate($im, rand(0,150), rand(0,150), rand(0,150));
				if ($i == 0)
					{
						imagestring($im, 28, rand(0,$widthpercar), rand(0,$height-14), $code[$i], $textcolor);
					}
				elseif ($i==$aant)
					{
						imagestring($im, 28, rand($min+8,$max), rand(0,$height-14), $code[$i], $textcolor);
					}
				else
					{
						imagestring($im, 28, rand($min+8,$max), rand(0,$height-14), $code[$i], $textcolor);
					}
				$codestr = $codestr . $code[$i];
				$i++;
			}


		if( $LINES_OVER == "1" )
			{
				// teken voor de zekerheid nog ff 2 lijnen OVER de text
				$i = 0;
				while( $i < 2 )
					{
						$noise_color = imagecolorallocate($im, rand(230,255), rand(230,255), rand(230,255));
						imageline($im, rand(0,$width), rand(0,$height), rand(0,$width), rand(0,$height), $noise_color);
						$i++;
					}
			}

		$_SESSION['captcha']=substr($codestr,0,$conf['captcha']['length']);
		
		header("Content-type: image/png");
		imagepng($im);
		imagedestroy($im);
	}
	
	function captcha ( )
		{
			if ( !isset ( $_POST['captcha'] ) ) $_POST['captcha'] = false;
			if ( !isset ( $_SESSION['captcha'] ) ) $_SESSION['captcha'] = "ABCDE"; 
			return (strtoupper($_SESSION['captcha']) == strtoupper($_POST['captcha']));
		}

function draw_email($conf,$override=null)
{
			if ( $override == null )
			 $code = ((isset($_SESSION['email']))?$_SESSION['email']:'ERROR');
			else
			 $code = $override;
			 
			$height = 30;
			$width  = strlen($code) * 15;
		    $im = @imagecreate($width, 20) or die("Cannot Initialize new GD image stream");
			$co = imagecolorallocate($im, 0, 0, 0);
			$bg = imagecolortransparent($im, $co);
			$textcolor = imagecolorallocate($im, rand(0,150), rand(0,150), rand(0,150));
			imagestring($im, 28, 1, 1, $code, $textcolor);
			header("Content-type: image/png");
			imagepng($im);
			imagedestroy($im);	
}
?>