<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















if ( !defined ( 'in_wdgss' ) )
 {
  exit("You`ll Missed This Action");
 }
 
  # {REPLACE}
 

class rss 
{
function __construct ($what='WDGSS') 
{
global $conf;
$this -> rss = "<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>

  <rss version=\"2.0\">
  <channel>
		<title>{$conf['site']['name']}</title>
		<link>{$conf['site']['url']}</link>
		<description>{$what}</description>
		<language>en-en</language>
		<lastBuildDate>"./*date("D, d F Y H:i:s O")*/ date("r")."</lastBuildDate>
		
		<generator>WesDeGroot Site System (WDGSS)</generator>
		<docs>http://blogs.law.harvard.edu/tech/rss</docs>
		<copyright>Copyright 2001-".date("Y")."</copyright>";
}
function item($title='Test Item', $desc='You Must Use Another Function Read The Readme!, btw my birthdate is the date',$date='Fri, 03 Aug 1990 04:55:00 +002',$url='http://www.wdgss.nl/help/rss')
{
$this -> rss .= "<item>
			<title>{$title}</title>
			<description>{$desc}</description>
			<pubDate>{$date}</pubDate>
			<link>{$url}</link>
			<guid isPermaLink=\"true\">{$url}</guid>

		</item>";
}
function get()
{
$this -> rss .= "</channel></rss>";
return $this -> rss;
}
}
?>
