<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















function _adminwiki() 
{
 global $conf,$lang,$url;

  if ( isset ( $_GET['id'] ) )
  {
        if ( isset ( $_POST['delete'] ) )
        {
           		$a = $conf['database']['db'] -> query("DELETE FROM `{$conf['database']['pref']}wiki` WHERE `id`='{$_POST['delete']}' LIMIT 1");
           		$a = $conf['database']['db'] -> query("DELETE FROM `{$conf['database']['pref']}wiki_link` WHERE `toid`='{$_POST['delete']}' LIMIT 1");
           		ga("{$url}admin/module/wiki");
        }

        if ( isset ( $_POST['text'] ) )
        {
              	$loging = (defined("login")?login:'Guest');

           		$a = $conf['database']['db'] -> query("UPDATE `{$conf['database']['pref']}wiki` SET `title`=`{$_POST['title']}`, `text`='{$_POST['text']}' WHERE `id`='{$_GET['id']}',`datetime`=NOW(), `by`='{$loging}' LIMIT 1");
           		ga("{$url}admin/module/wiki");
        }
   		$a = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}wiki` WHERE `id`='{$_GET['id']}' LIMIT 1");
			$b = $conf['database']['db'] -> fetch($a, 'array');
      echo "<form method='post'><input type='hidden' name='id' value='{$_GET['id']}'><input type='text' name='title' value='{$b[0]['title']}'><br><textarea name='text'>{$b[0]['text']}</textarea><br><input type='submit' value='Update/Back'></form>
            <form method='post'><input type='hidden' name='delete' value='{$_GET['id']}'><input onclick=\"return confirm('Sure Delete');\" type='submit' value='Delete'></form>";
  }
  else
  {
   		$a = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}wiki`");
			$b = $conf['database']['db'] -> fetch($a, 'array');
			echo "<h1>wiki Topics</h1>";
			for($i=0; $i<sizeof($b); $i++)
        {
          echo "<a href='{$url}admin/module/wiki/{$b[$i]['id']}'>Edit/Delete: ({$b[$i]['id']}) {$b[$i]['title']}</a><br>";
        }
      echo "<hr>";
      
      	$username = (defined("login")?login:'Guest');

      if ( isset ( $_POST['xtext'] ) ) 
       {
           		$a = $conf['database']['db'] -> query("INSERT INTO `{$conf['database']['pref']}wiki` (`id`,`title`,`text`,`by`,`datetime`) VALUES ('','{$_POST['title']}', '{$_POST['xtext']}','{$username}',NOW());");
           		$id=$conf['database']['db'] -> id();
           		$a = $conf['database']['db'] -> query("INSERT INTO `{$conf['database']['pref']}wiki_link` (`id`,`title`,`toid`) VALUES ('','{$_POST['title']}', '{$id}');");           		
           		ga("{$url}admin/module/wiki");
       }
      else
       {
        echo "<form method='post'>Title: <input type='text' name='title'><br>Text: <textarea name='xtext'></textarea><br><input type='submit'></form>";
       }
   }
}

?>