<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################
















 if ( isset ( $_GET['what'] ) && isset ( $_GET['id'] ) )
	{ 
		$what	=	$_GET['what']; 
		$id		=	$_GET['id'];
		$G 		=   ( ( $what == 'topic' ) ? 'text' : 'reaction' ) ;
		
		$s = "SELECT * FROM `{$conf['database']['pref']}forum_{$what}s` WHERE `id`='{$id}' LIMIT 0,1;";
		$se = $conf['database']['db'] -> query($s);
		$se = $conf['database']['db'] -> fetch ( $se, 'array' );
		$se = $se[0];
		$text = $se[$G];
		$text = preg_replace("#\\\"#","\"",$text);
		$text = preg_replace('#\\\'#',"'",$text);
		$text = preg_replace('@style="" line-through;\\\\\"=""@','style="text-decoration: line-through;"',$text);
		$text = preg_replace('#\"#','"',$text);
		$text=stripslashes($text);
		$text=stripslashes($text);
				
		if ( isset ( $_POST['editfield'] ) && isset ( $_POST['what'] ) )
			{
				$texta = $_POST['editfield'];
				$texta = preg_replace("#\\\"#","\"",$texta);
				$texta = preg_replace('#\\\'#',"'",$texta);
				$texta = preg_replace('@style="" line-through;\\\\\"=""@','style="text-decoration: line-through;"',$texta);
				$texta = preg_replace('#\"#','"',$texta);
				$texta = stripslashes($texta);
				$texta = stripslashes($texta);

				if ( 
					($se['by'] == @$_SESSION['login']) Or
					(@$_SESSION['status'] >= 3)
				   )
					{
						$sew = "
						UPDATE 
							`{$conf['database']['pref']}forum_{$_POST['what']}s` 
						SET 
							`{$G}`='{$texta}".(($se['by']!=$_SESSION['login'])?'<br>Edit: ' . $_SESSION['login']:null)."',
							`datetime`=NOW()
						WHERE 
							`id`='{$id}' 
						LIMIT 1;";
						$seww = $conf['database']['db'] -> query($sew);
						if ( $seww ) 
						 {
						 $S = ( $what == 'topic' ) ? $id : $se['topicid'];
						 ga ( $url . "forum/iid/" . $S );
						 }
					}
			}
		
		$se = $conf['database']['db'] -> query($s);
		$se = $conf['database']['db'] -> fetch ( $se, 'array' );
		$se = $se[0];
		$text = $se[$G];
			

		if ( 
			($se['by'] == @$_SESSION['login']) Or
			(@$_SESSION['status'] >= 3)
		   )
		{
?>

<form method='post' action='<?php echo $conf['site']['url'] . 'forum/edit/'.$what.'/'.$id; ?>'>
	<input type='hidden' name='what' value='<?php echo $_GET['what']; ?>'>
	<input type='hidden' name='id' value='<?php echo $_GET['id']; ?>'>
	<textarea id='editfield' rows='50' cols='150' name='editfield'><?php echo ( isset($text) ? $text : null ); ?></textarea>
	<?php echo wysiwyg('editfield'); ?>
	<input type='submit' value='<?php echo $lang['admin']['save']; ?>'>
</form>

<?php
	}
	}
?>