<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















 $a = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}forum` ORDER BY `id` ASC");
 $a = $conf['database']['db'] -> fetch($a, 'array');
?>
<table>
 <tr>
  <td>
   <?php echo $lang['forum']['cat']; ?>
  </td>
  <td>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </td>
  <td>
   <?php echo $lang['forum']['topics']; ?>
  </td>
  <td>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </td>
  <td>
   <?php echo $lang['forum']['last']; ?>
  </td>
 </tr>
<?php
for ( $i=0; $i<sizeof($a); $i++ )
{
?>
 <tr>
  <td>
   <a href='<?php echo $conf['site']['url']; ?>forum/cat/<?php echo $a[$i]['id']; ?>'><?php echo $a[$i]['catname']; ?></a>
  </td>
  <td>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </td>
  <td>
   <?php
    #see topics
    $e = $conf['database']['db'] -> query("SELECT `id` FROM `{$conf['database']['pref']}forum_topics` WHERE `catid`='{$a[$i]['id']}'");
    $e = $conf['database']['db'] -> num ( $e );
    if (is_numeric($e)) echo $e;
    Else               echo '0';
   ?>
  </td>
  <td>
	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  </td>
  <td>
    <?php
    #Last/Reaction
    $e = $conf['database']['db'] -> query("SELECT `by`,`topicid` FROM `{$conf['database']['pref']}forum_reactions` WHERE `catid`='{$a[$i]['id']}' ORDER BY `datetime` DESC");
    $e = $conf['database']['db'] -> fetch ( $e, 'array' );
    
    if ( isset ( $e[0]['by'] ) && isset ( $e[0]['topicid'] ) )
    {
    $z = $conf['database']['db'] -> query("SELECT `name`,`lastpost` FROM `{$conf['database']['pref']}forum_topics` WHERE `id`='{$e[0]['topicid']}'");
    $z = $conf['database']['db'] -> fetch ( $z, 'array' );
    if ( is_array($z[0])) {
    $topic = $z[0]['name'];
     
     echo "<a href='{$conf['site']['url']}profile/" . $e[0]['by'] . "'>" . $e[0]['by'] . "</a> @ <a href='{$conf['site']['url']}forum/{$a[0]['catname']}/{$e[0]['topicid']}'>" . $topic . "</a>"; 
    }else{ echo 'None'; }
    }
    else
    {
    echo 'None';
    }
    ?>
  </td>
 </tr>
<?php
}
?>
</table>