<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















function p_o_s_t ( ) 
{
	global $_POST,$_GET,$conf;
	$username = (defined("login")?login:'Guest');
	$sticky   = (isset($_POST['sticky'])?$_POST['sticky']:'0');
	$protected= (isset($_POST['protected'])?$_POST['protected']:'0');
	$closed   = (isset($_POST['closed'])?$_POST['closed']:'0');

	$sql = "INSERT INTO `{$conf['database']['pref']}forum_topics` ( `id` ,`catid` ,`name` ,`by` ,`datetime` ,`lastpost` ,`ip` ,`text` ,`sticky` ,`protected` ,`closed` )\nVALUES ( NULL , '{$_POST['cat']}', '{$_POST['name']}', '{$username}', NOW(), NOW(), '" . encodeip(getip(true)) . "', '{$_POST['text']}', '{$sticky}', '{$protected}', '{$closed}');";
	if ( $conf['database']['db'] -> query ( $sql ) )
		ga($conf['site']['url'] . "forum/iid/" . $conf['database']['db'] -> id());
	else
		echo $lang['forum']['topicerror'];
}
// post: name (topicname)
// post: text (message)
// admin: post: sticky: sticky?
// admin: post: protected: protected?
if ( 
	isset ( $_POST['name'] ) && 
	isset ( $_POST['text'] )
   )
{
 if ( captcha() Or defined("login") )
	p_o_s_t();
 else
	echo $lang['forum']['captcha'];
}
?><br>
<form method="post" action="<?php echo $conf['site']['url']; ?>forum/new/<?php echo $_GET['cat']; ?>">
<input type='hidden' name='cat' value='<?php echo $_GET['cat']; ?>'>
<table>
	<tr>
		<td>
			<?php echo $lang['forum']['name']; ?>
		</td>
		<td>
			<input type='text' name='name'>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $lang['forum']['message']; ?>
		</td>
		<td>
			<?php echo wysiwyg("text"); ?>
			<textarea name='text' id='text' rows='10' cols='45'></textarea>
		</td>
	</tr>
<?php
	if ( !defined ( "login" ) ) {
?>
	<tr>
		<td>
			<img src='<?php echo $conf['site']['url']; ?>captcha.png'>
		</td>
		<td>
			<input type='text' name='captcha'>
		</td>
	</tr>
<?php
}
$level = ((isset($member['status'])?$member['status']:1));
?>
	<tr>
		<td>
			<?php echo $lang['forum']['sticky']; ?> 
		</td>
		<td>
			<select name="sticky">
				<option value="0">
					<?php echo $lang['forum']['no']; ?>
				</option>
				<?php if ( $level >= 3 ) { ?>
				<option value="1">
					<?php echo $lang['forum']['yes']; ?>
				</option>
				<?php } ?>
			</selected>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $lang['forum']['protected']; ?> 
		</td>
		<td>
			<select name="protected">
				<option value="0">
				 <?php echo $lang['forum']['everyone']; ?>
				</option>
				<?php if ( $level >= 1 ) { ?>
				<option value="1">
				 <?php echo $lang['forum']['loggedin']; ?>
				</option>
				<?php } ?>
				<?php if ( $level >= 2 ) { ?>
				<option value="2">
				 <?php echo $lang['forum']['vips']; ?>
				</option>
				<?php } ?>
				<?php if ( $level >= 3 ) { ?>
				<option value="3">
				 <?php echo $lang['forum']['moderators']; ?>
				</option>
				<?php } ?>
				<?php if ( $level == 4 ) { ?> 
				<option value="4">
				 <?php echo $lang['forum']['admins']; ?>
				</option>
				<?php } ?>
			</select>
		</td>
	</tr>
	<tr>
		<td>
			<?php echo $lang['forum']['closed']; ?> 
		</td>
		<td>
			<select name="closed">
				<option value="0">
				 <?php echo $lang['forum']['no']; ?>
				</option>
				<?php if ( $level >= 3 ) { ?>
				<option value="1">
				 <?php echo $lang['forum']['yes']; ?>
				</option>
				<?php } ?>
			</select>
		</td>
	</tr>
	<tr>
		<td>
			<input type="reset" value="<?php echo $lang['forum']['reset']; ?>">
		</td>
		<td>
			<input type="submit" value="<?php echo $lang['forum']['submit']; ?>">
		</td>
	</tr>
</table>
</form>