<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















	$a = @$_GET['act'];
	switch ( $a )
		{
			case 'new':
				include 'modules/forum/new.php';
			break;
			
			case 'post':
				include 'modules/forum/post.php';
			break;
			
			case 'topic':
				echo "<a href='{$conf['site']['url']}forum.pag'>Forum</a>";
				if ( isset ( $_GET['cat'] ) )
				 echo " => <a href='{$conf['site']['url']}forum/cat/{$_GET['cat']}'>{$_GET['cat']}</a>";
				echo "<br>";
				include 'modules/forum/topic.php';
			break;
			
			case 'edit':
				include 'modules/forum/edit.php';
			break;

			case 'del':
				include 'modules/forum/del.php';
			break;

			case 'cat':
				echo "<a href='{$conf['site']['url']}forum.pag'>Forum</a><br>";
				include 'modules/forum/catagory.php';
			break;
			
			default:
				include 'modules/forum/main.php';
			break;
		}
?>