<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















 //TEST Haai<br>ik<br>ben een test :O<br><p><span style="color: rgb(0, 153, 204);">IK BEN BLAUW</span><br></p>
if  (
		isset ( $_POST['topicid'] ) &&
		isset ( $_POST['catid'] ) &&
		isset ( $_POST['message'] )
	)
	{
		$username = ( defined ( "login" ) ? login : "Guest" ) ;
		$topicid  = $_POST [ 'topicid' ] ;
		$catid    = $_POST [ 'catid' ]   ;
		$message  = $_POST [ 'message' ] ;
		$message  = strip ( $message )   ;
		 
		if ( $username == "Guest" ) 
			{
				if ( !captcha() )
					{
						$GO = $conf['site']['url'] . "forum/iid/" . $topicid;
						ga($GO);
						exit;
					}
			}

		$a = $conf['database']['db'] -> query($q = "INSERT INTO `{$conf['database']['pref']}forum_reactions` ( `id` , `topicid` , `catid` , `by` , `datetime` , `ip` , `reaction` )\nVALUES ( NULL , '{$topicid}', '{$catid}', '{$username}', NOW( ) , '" . encodeip ( getip ( true ) ) . "', '{$message}' );");
		$a = ($a) ? 'Posted':'Error: ' . mysql_error();
		$e = $conf['database']['db'] -> query("UPDATE `{$conf['database']['pref']}forum_topics` SET `lastpost` = NOW( ) WHERE `id` = '{$topicid}' ");
		$GO = $conf['site']['url'] .  "forum/iid/" . $topicid;
	}
else
	{
		$GO = ($conf['site']['url'] . "forum.pag");
	}
	ga($GO);
?>