<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















 if ( isset ( $_GET['id'] ) )
 {
	#fetch Topic
	$a = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}forum_topics` WHERE `id`='{$_GET['id']}' Or `name`='{$_GET['id']}'");
	$c = $conf['database']['db'] -> num($a, 'rows');

	if ( $c > 0 )
		{ 
			$a = $conf['database']['db'] -> fetch($a, 'array'); 
		}
	Else
		{
			ga($conf['site']['url'] . "forum.pag");
			exit; 
		}
		
	#fetch Poll???
	$b = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}forum_polls` WHERE `postid`='{$a[0]['id']}'");
	$c = $conf['database']['db'] -> num($b, 'rows');
	if ( $c > 0 )
		{
			$b = $conf['database']['db'] -> fetch($b, 'array');
		}
	else
		{
			unset($b);
		}
		
		$a[0]['text'] = preg_replace("#\\\"#","\"",$a[0]['text']);
		$a[0]['text'] = preg_replace('#\\\'#',"'",$a[0]['text']);
		$a[0]['text'] = preg_replace('@style="" line-through;\\\\\"=""@','style="text-decoration: line-through;"',$a[0]['text']);
		$a[0]['text'] = preg_replace('#\"#','"',$a[0]['text']);
		$a[0]['text'] = stripslashes($a[0]['text']);
		
?>
<div class='forum'>
 <div class='forum_title'>
  <span style='float: left; '>
   <?php echo $a[0]['name']; ?>
  </span>
  <span style='float: right;'>
   <?php echo nldate($a[0]['datetime']); ?>
   <?php
    If ( isset ( $_SESSION['login'] ) )
    {
     if ( ( $_SESSION['login'] == $a[0]['by'] ) Or 	(@$_SESSION['status'] >= 3) ) 
     {
      echo '&nbsp;&nbsp;<a href=\'' . $conf['site']['url'] . 'forum/edit/topic/' . $a[0]['id'] . '\'>Edit</a>';
      echo '&nbsp;&nbsp;<a href=\'' . $conf['site']['url'] . 'forum/del/topic/' . $a[0]['id'] . '\' onclick="return confirm(\'' . sprintf($lang['forum']['suredel'],$a[0]['id']) . '\');">Delete</a>';
	 }
    }
   ?>
  </span>&nbsp; 
 </div>
 <br><br>
 <table>
  <tr>
   <td>
    <?php echo $a[0]['by']; $_SESSION['avatar']=$a[0]['by']; ?><br>
    <img width='150' height='150' src='<?php echo $conf['site']['url']; ?>avatar/<?php echo $a[0]['by']; ?>'>
   </td>
   <td>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   </td>
   <td>
    <div class='forum_message'>
     <?php
     if ( $status >= $a[0]['protected'] ) {
     ?>
     <?php echo (stripslashes($a[0]['text'])); ?><br>
     <form method='post' action='<?php echo $conf['site']['url']; ?>forum/poll'>
		<?php
		if ( isset ( $b ) )
		{
		?>
		<input type='hidden' name='poll' value='<?php echo $b[0]['id']; ?>'>
		<?php
		 for ( $i=1; $i<11; $i++ )
		 {
		  $x = @$b[0]['TXT' . $i];
		  if (!empty($x) && isset($x)) 
			echo "<input type='radio' name='ans' id='{$i}'><label for='{$i}'>{$b[0]['TXT' . $i]}</label><br>";
		 }
		?>
		<input type='submit' value='<?php echo $lang['forum']['vote']; ?>'> <small>(<a href='forum.pag?act=poll&s&id=<?php echo $b[0]['id']; ?>'><?php echo $lang['forum']['result']; ?></a>)</small>
		<?php
		}
		?>
     </form>
     <?php
     }
     else
     {
		echo sprintf($lang['forum']['noaccess'],$status,$a[0]['protected']);
     }
     ?>
    </div>
   </td>
  </tr>
 </table>
<?php
     if ( $status >= $a[0]['protected'] ) {
?>
 <div class='reactions'>
  <?php
 	#fetch reactions
	$d = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}forum_reactions` WHERE `topicid`='{$a[0]['id']}' ORDER BY `datetime` DESC");
	$c = $conf['database']['db'] -> num($d, 'rows');

	if ( $c != 0 )
		$d = $conf['database']['db'] -> fetch($d, 'array');
	Else
		{
			echo $lang['forum']['noreactions'];
			unset($d);
		}
	
	if ( isset ( $d ) ) 
	 {
	  for ( $i=0; $i<sizeof($d); $i++ )
	   {

?>
 <div class='forum_title'>
  <span style='float: left; '>
   Re: <?php echo $a[0]['name']; ?>
  </span>
  <span style='float: right;'>
   <?php echo nldate($d[$i]['datetime']); ?>
   <?php
    If ( isset ( $_SESSION['login'] ) )
    {
     if ( ( $_SESSION['login'] == $d[$i]['by'] ) Or 	(@$_SESSION['status'] >= 3) ) 
     {
      echo '&nbsp;&nbsp;<a href=\'' . $conf['site']['url'] . 'forum/edit/reaction/' . $d[$i]['id'] . '\'>Edit</a>';
      echo '&nbsp;&nbsp;<a href=\'' . $conf['site']['url'] . 'forum/del/reaction/' . $d[$i]['id'] . '\' onclick="return confirm(\'' . sprintf($lang['forum']['suredel'],$d[$i]['id']) . '\');">Delete</a>';
	 }
    }
   ?>
  </span>&nbsp;
 </div>
 <br><br>
 <table>
  <tr>
   <td>
    <?php echo $d[$i]['by']; $_SESSION['avatar'] = $d[$i]['by']; ?><br>
    <img width='150' height='150' src='<?php echo $conf['site']['url']; ?>avatar/<?php echo $d[$i]['by']; ?>'>
   </td>
   <td>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   </td>
   <td>
    <div class='forum_reaction'>
     <?php 
					  $d[$i]['reaction'] = preg_replace("#\\\"#","\"",$d[$i]['reaction']);
					  $d[$i]['reaction'] = preg_replace('#\\\'#',"'",$d[$i]['reaction']);
					  $d[$i]['reaction'] = preg_replace('@style="" line-through;\\\\\"=""@','style="text-decoration: line-through;"',$d[$i]['reaction']);
					  $d[$i]['reaction'] = preg_replace('#\"#','"',$d[$i]['reaction']);
					  $d[$i]['reaction'] = stripslashes($d[$i]['reaction']);
	echo stripslashes($d[$i]['reaction']); 
     ?>
    </div>
   </td>
  </tr>
 </table>
<?php
	   }
	 }
  ?>
 <div class='forum_title'>
   <?php echo $lang['forum']['post']; ?>
 </div>
 <br><br>
 <table>
  <tr>
   <td>
    &nbsp;
   </td>
   <td>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   </td>
   <td>
    <div class='forum_reaction'>
     <!-- BEG POST -->
		<?php 
		 if ( !$a[0]['closed'] )
		 {
		?>
		 <form method='POST' action='<?php echo $conf ['site']['url']; ?>forum/post'>
			<input type='hidden' name='topicid' value='<?php echo $_GET['id']; ?>'>
			<input type='hidden' name='catid' value='<?php echo $a[0]['catid']; ?>'>
			<table>
				<tr>
					<td>     
						<?php echo $lang['forum']['username']; ?>:
					</td>
					<td>
						<?php if(defined("login")) echo login; else echo $lang['forum']['guest']; ?>
						<input type='hidden' name='username' value='<?php if(defined("login")) echo login; else echo "Guest"; ?>'>
					</td>
				</tr>
			<?php
				 if (!defined("login")) 
				  {
			?>
				<tr>
					<td>     
						<img src='<?php echo $conf['site']['url']; ?>captcha.png'>
					</td>
					<td>
						<input type='text' name='captcha'>
					</td>
				</tr>
			<?php
				  }
			?>
</table>
						<?php echo $lang['forum']['message']; ?>:
<br>						<?php echo wysiwyg('message'); ?>
						<textarea id='message' name='message' rows='10' cols='50'></textarea>
<table>
				<tr>
					<td>     
						&nbsp;
					</td>
					<td>
						<input type='submit' value='Post'>
					</td>
				</tr>
			</table>
		</form>
		<?php
		}
		else
		{
		 echo $lang['forum']['closed'];
		}
		?>
     <!-- ENd POST -->
    </div>
   </td>
  </tr>
 </table>
 </div>
</div>
<?php
}
 }
 else
 {
  ga($conf['site']['url'] . "forum.pag");
 }
?>