<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















function _adminhelp() 
{
 global $conf,$lang,$url;

  if ( isset ( $_GET['id'] ) )
  {
        if ( isset ( $_POST['delete'] ) )
        {
           		$a = $conf['database']['db'] -> query("DELETE FROM `{$conf['database']['pref']}help` WHERE `id`='{$_POST['delete']}' LIMIT 1");
           		ga("{$url}admin/module/help");
        }

        if ( isset ( $_POST['text'] ) )
        {
           		$a = $conf['database']['db'] -> query("UPDATE `{$conf['database']['pref']}help` SET `text`='{$_POST['text']}' WHERE `id`='{$_GET['id']}' LIMIT 1");
           		ga("{$url}admin/module/help");
        }
   		$a = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}help` WHERE `id`='{$_GET['id']}' LIMIT 1");
			$b = $conf['database']['db'] -> fetch($a, 'array');
      echo "<form method='post'><textarea name='text'>{$b[0]['text']}</textarea><br><input type='submit' value='Update/Back'></form>
            <form method='post'><input type='hidden' name='delete' value='{$_GET['id']}'><input onclick=\"return confirm('Sure Delete');\" type='submit' value='Delete'></form>";
  }
  else
  {
   		$a = $conf['database']['db'] -> query("SELECT * FROM `{$conf['database']['pref']}help`");
			$b = $conf['database']['db'] -> fetch($a, 'array');
			echo "<h1>Help Topics</h1>";
			for($i=0; $i<sizeof($b); $i++)
        {
          echo "<a href='{$url}admin/module/help/{$b[$i]['id']}'>Edit/Delete: {$b[$i]['id']}</a><br>";
        }
      echo "<hr>";
      
      if ( isset ( $_POST['xtext'] ) ) 
       {
           		$a = $conf['database']['db'] -> query("INSERT INTO `{$conf['database']['pref']}help` (`id`,`text`) VALUES ('{$_POST['iid']}', '{$_POST['xtext']}');");
           		ga("{$url}admin/module/help");
       }
      else
       {
        echo "<form method='post'>Id: <input type='text' name='iid'><br>Text: <textarea name='xtext'></textarea><br><input type='submit'></form>";
       }
   }
}

?>