<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















function _adminnews() {
#echo dump($_GET);
		global $conf,$lang,$member;
		$u = $conf['site']['url'] . "admin/news";
		$r = '<a href=\'' . $u . '\'>&lt;--</a><br /><br />';
		#// wysiwyg = wysiwyg('textarea') //
		if ( isset ( $_GET['editpage'] ) )
			{
				if ( isset ( $_POST['opage'] ) && isset ( $_POST['page'] ) && isset ( $_POST['content'] ) )
					{
						$_POST['content'] = preg_replace("#\\\"#","\"",$_POST['content']);
						$w = $conf['database']['db'] -> query ( "UPDATE `{$conf['database']['pref']}news` SET `name`='" . secure($_POST['page']) . "', `text`='" . ($_POST['content']) . "' WHERE `name`='" . secure($_POST['opage']) . "'");
						if ($w)
						{
							$r .= $lang['news']['editedpage'];
						}
						else
						{
							$r .= $lang['news']['noteditedpage'];
						}
					} 
				else
					{
						$w = $conf['database']['db'] -> query ( "SELECT `name`,`text` FROM `{$conf['database']['pref']}news` WHERE `name`='{$_GET['editpage']}'" );
						$w = $conf['database']['db'] -> fetch ( $w, 'array' );
						$w = $w[0];
						$r .= "<form method='post' action='{$u}editpage/{$_GET['editpage']}'><table><tr><td>{$lang['news']['title']}</td><td><input type='hidden' name='opage' value='{$w['name']}'><input type='text' name='page' value='{$w['name']}'></td></tr><tr><td>{$lang['news']['content']}</td><td><textarea id='ncontent' name='content' rows='25' cols='50'>{$w['text']}</textarea></td></tr><tr><td></td><td><input type='submit' value='{$lang['news']['save']}'></td></tr></form></table>" . wysiwyg('ncontent');
					}
			}
		elseif ( isset ( $_GET['newpage'] ) )
			{
				if ( isset ( $_POST['page'] ) && isset ( $_POST['content'] ) )
					{
						$_POST['content'] = preg_replace("#\\\"#","\"",$_POST['content']);
						$w = $conf['database']['db'] -> query ( "INSERT INTO `{$conf['database']['pref']}news` ( `id`,`by`,`datetime`,`name`,`text` ) \n VALUES ( NULL, '" . (isset($member['realname']) ? $member['realname'] : 'Admin') . "', CURRENT_TIMESTAMP, '{$_POST['page']}','{$_POST['content']}' );");
						if ($w)
							{
								$r .= $lang['news']['createdpage'];
							}
						else
							{
								$r .= $lang['news']['notcreatedpage'];
							}
					} 
				else
					{
						$r .= "<form method='post' action='{$u}newpage'><table><tr><td>{$lang['news']['title']}</td><td><input type='text' name='page'></td></tr><tr><td>{$lang['news']['content']}</td><td><textarea id='content' name='content' rows='25' cols='50'></textarea></td></tr><tr><td></td><td><input type='submit' value='{$lang['news']['save']}'></td></tr></form></table>" . wysiwyg('content');
					}
			}
		elseif ( isset ( $_GET['deletepage'] ) )
			{
				$_GET['deletepage'] = secure($_GET['deletepage']);
				$w = $conf['database']['db'] -> query ( "DELETE FROM `{$conf['database']['pref']}news` WHERE `name`='{$_GET['deletepage']}';");
				if ($w)
					{
						$r .= $lang['news']['deletedpage'];
					}
				else
					{
						$r .= $lang['news']['notdeletedpage'];
					}
			}
		else
			{
				$w = $conf['database']['db'] -> query ( "SELECT `name` FROM `{$conf['database']['pref']}news`" );
				$w = $conf['database']['db'] -> fetch ( $w, 'array' );

				$r .= '<table>';
				if ( $w!="the table is empty!" )
				{
 				for($i=0; $i<sizeof($w); $i++)
					{
						$r .= "<tr><td>{$w[$i]['name']}</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td><td><a href='{$u}editpage/{$w[$i]['name']}'>{$lang['news']['edit']}</a></td><td>&nbsp;&nbsp;</td><td><a href='{$u}deletepage/{$w[$i]['name']}' onclick=\"return confirm('" . sprintf($lang['news']['suredelpage'],$w[$i]['name']) . "');\">{$lang['news']['del']}</a></td></tr>";
					}
				}
				$r .= '</table>';
				$r .= "<br /><a href='{$u}newpage'>{$lang['news']['newpage']}</a>";
			}
		return $r;
}
?>