<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















if(isset($_GET['load']) && isset($_GET['f'])) {
 if ( preg_match("#JS#",$_GET['load']) && !preg_match("#(\.\.)#",$_GET['load']) && !preg_match("#(h|H)(t|T)(t|T)(p|P|ps|PS|pS|Ps)#",$_GET['load'])) {
  header("content-type: text/javascript"); 
  include('modules/photobook/scripts/' . $_GET['f']); 
  exit; 
 }
 if ( preg_match("#CSS#",$_GET['load']) ) {
  header("content-type: text/css"); 
  include('modules/photobook/css/jd.gallery.css'); 
  exit; 
 }
}
error_reporting(E_ALL);

$effect = 'slide(right)';
$time   = isset($_GET['time'])?$_GET['time']:'2';

function _debug($w) {
//
}

_debug('Loading...');
_debug('Check Dirs!');
	$allowed = array();
	$f=0;
	$_q=opendir('data/photobook/');
	while ( ( $e = readdir ( $_q ) ) !== false )
		{
			if ( 
					$e != '.' && 
					$e != '..' &&
					!preg_match("#(\?|\|)#",$e)
				)
					{
						$f++;
						$allowed[] = $e;
						_debug('Found Album: ' . $e);
					}
		}
		
		if ( $f == 0 )
		 { 
		  _debug('FATALL ERROR CAN`T LOAD ALBUMS');
		  echo('Can`t Load Albums! (empty?)');
		 }
_debug('Albums Loaded See Those: ' . implode(',',$allowed));

if ( isset ( $_GET['seebook'] ) )
	{
		_debug('?seebook!');

		if ( !file_exists( $LFD = 'data/photobook/' . $_GET['seebook'] . '/password.txt' ) ) 
		{
					if ( in_array ( $_GET['seebook'], $allowed ) )
						{
							_debug('Ok!');
							$ok   = true;
							$book = $_GET['seebook'];
						}
			}
		else
			{
				if ( isset ( $_GET['password'] ) )
					{
					$pass = file_get_contents($LFD);
					if (   $_GET['password']   ==   $pass  && 
					in_array ( $_GET['seebook'], $allowed ) )
							{
								_debug('Ok!');
								$ok   = true;
								$book = $_GET['seebook'];
							}
					}
				else
					{
					?>
						<form method='get' action='<?php echo $conf['site']['url']; ?>photobook.pag'>
							<input type='hidden' name='seebook' value='<?php echo $_GET['seebook']; ?>'>
							<?php echo $lang['photobook']['password']; ?>: <input type='password' name='password'>
							<input type='submit' value='<?php echo $lang['photobook']['enter']; ?>'>
						</form>
					<?php
					}
			}
	}

if ( isset ( $ok ) ) 
{
_debug('$Ok!');
$f  = opendir('data/photobook/' . $book);
echo "<a href='{$conf['site']['url']}!photobook'>{$lang['site']['photobook']}</a>";
if ( file_exists ( $LFD = 'data/photobook/' . $book . '/extra.txt' ) )
	include $LFD;
?>
		<link rel="stylesheet" href="<?php echo $conf['site']['url']; ?>photobook.pag?load=CSS&f=default" type="text/css" media="screen" charset="utf-8" />
		<script src="<?php echo $conf['site']['url']; ?>photobook.pag?load=JS&f=mootools-1.2.1-core-yc.js" type="text/javascript"></script>
		<script src="<?php echo $conf['site']['url']; ?>photobook.pag?load=JS&f=mootools-1.2-more.js" type="text/javascript"></script>
		<script src="<?php echo $conf['site']['url']; ?>photobook.pag?load=JS&f=jd.gallery.js" type="text/javascript"></script>
		
		<script type="text/javascript">
			function startGallery() {
				var myGallery = new gallery($('myGallery'), {
					timed: true
				});
			}
			window.addEvent('domready',startGallery);
		</script>
<div id="myGallery">
<?php
//echo "<script type=\"text/javascript\" language=\"JavaScript\" src=\"{$conf['site']['url']}photobook.pag?load=slide\"></script><textarea id=\"piclist\" style=\"visibility:hidden\">\r\n";
// USE ##Beautiful Sunset <time=5> <trans=slide(right)>
$ff = 0;
$tr = 1;
$si = '400';
while ( ( $e = readdir ( $f ) ) !== false )
{
 if ( 
		$e != '.' && 
		$e != '..' && 
		$e != 'index.php' && 
		!is_dir($e) && 
		preg_match("#\.(J|j)(P|p)(G|g)#",$e)
	)
 {
  //if ( $tr==1 ) echo "<tr>";
  $e = preg_replace("#\.(J|j)(P|p)(G|g)#",null,$e);
  $z = $e;
  // echo '<td>';
  //echo '<img width="' . $si . '" height="' . $si . '" src="' . $url . '/photobook.pag?photobook='.$book.'&img=' . $e . '" alt="' . $z . '"><br>';
  //echo '<font style="x-face:Script" size="6">' . $z . '</font><br><br>';
  echo "
  
				<div class=\"imageElement\">
					<h3>{$z}</h3>
					<p>&nbsp;</p>
					<a href=\"#\" title=\"open image\" class=\"open\"></a>
					<img src=\"{$url}photobook/{$book}/{$e}\" class=\"full\" />
					<img src=\"{$url}photobook/{$book}/{$e}\" class=\"thumbnail\" />
				</div>";
  // echo '</td>';
  //if ( $tr==2 ) echo "</tr>";
  
  $tr++;
  if ( $tr > 2 ) $tr = 1;
  
  $ff++;
 }
}
echo "</div>";
if ( $ff < 1 )
 echo "<!-- --><marquee>Update In Progress!</marquee><!-- -->";
}
else
{
	_debug('List Albums!');
		for ( $i=0; $i<sizeof($allowed); $i++ )
			{	
				echo "<a href='{$conf['site']['url']}photobook/{$allowed[$i]}'>{$allowed[$i]}</a><br>";
			}
}
_debug('print');
?>