<?php 
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















if ( defined ( "login" )) 
{
	if ( $member['status'] == '4' )
	 {
	  if (!isset ( $_SESSION['login_admin'] ))
	   {
	    $_SESSION['login_admin'] = true;
	    ga($conf['site']['url'] . "admin");
	   }
	 }
	 else
	 {
	   echo "No Access!";
	 }
}

if	( isset ( $_SESSION['login_admin'] ) )
	{
		$a = isset($_GET['act'])?$_GET['act']:null;
		echo admin($a);
	}
else
	{
		ga ( $conf['site']['url'] . "page/login" );
		echo admin_login();
	}
?>