<?php
      ####################################################
      ####################################################
      ###                                              ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###    # # # # # # # # # # # # # # # # # # # #   ###
      ###     #     WDGSS Required File     # # # # #  ###
      ###    # Please No Change In This File # # # #   ###
      ###   # # # # # # # # # # # # # # # # # # # #    ###
      ###  # # # # # # # # # # # # # # # # # # # #     ###
      ###                                              ###
      ####################################################
      ####################################################
      ### WARNING DO NOT EDIT THIS FILE, THAT MISMATCH ###
      ### THE USABILITY OF WDGSS, WE DO NOT GIVE ----- ###
      ### SUPPORT FOR EDITTED FILES!!!!!!!!!!!!!!!!!!! ###
      ####################################################
      ####################################################
	  ### STARTED BY: Wesley De Groot (wes@wdgss.nl)   ###
	  ### FILE VERSION: 6.0.0.1-25                     ###
	  ### WDGSS VERSION: 6.0.0.1 Final                 ###
      ####################################################
	  ### LAST EDIT BY: Wesley De Groot (wes@wdgss.nl) ###
	  ### LAST REVISION: 20:12 @ 15 / 09 / 2010        ###
	  ####################################################
	  ####################################################















	# XSS FIX & UBB
		
	function xss ( $v )
	{
		if (!is_array($v))
			{
				$v = xses ( $v ) ;
			}
		else
			{
				// try to catch!
				if ( isset ( $v[0] ) && isset ( $v[1] ) ) // Array must be minimal 2 to be a post/get array
					{
						for ( $i=0; $i<sizeof($v); $i++ )
							{
								$v[$i] = xses($v[$i]);
							}
					}
				else
					{
						// Attempt 2!
						foreach ( $v As $a => $b ) 
							{
								$v[$a] = xses ( $b );
							}
					}
			}
			#BUGFIX
			return $v;
	}
	
	function xses ( $v ) 
	 { 
		$v = preg_replace("#(java)script\:#", null, $v);
		$v = preg_replace("#(alert|confirm|unescape|document\.cookie|window\.location)#", null, $v);
		$v = preg_replace("#\<(\/script|script)(.*)\>#", null, $v);
		$v = preg_replace("#OR '1'='1'#", null, $v);
		$v = preg_replace("#OR 1=1#", null, $v);
		$v = preg_replace("#`#", null, $v);
//		$v = secure($v);
		return $v;
	 }
	
	if ( !preg_match ( "/(a|A)(d|D)(m|M)(i|I)(n|N)/", $_SERVER['REQUEST_URI'] ) )
		{
			foreach ( $_POST As $p => $v )
				{
					$_POST[$p] = xss ( $v ) ;
				}
	 
			foreach ( $_GET As $p => $v )
				{
					$_GET[$p]  = xss ( $v ) ;
				}
		}
?>